export interface SubtitleCue {
  start: number;
  end: number;
  japanese: string;
  romaji: string;
  myanmar: string;
}

export interface Lesson {
  id: string;
  title: string;
  titleMm: string;
  videoId: string;
  level: string;
  subtitles: SubtitleCue[];
}

export const lessons: Lesson[] = [
  {
    id: "1",
    title: "あとひとつ / FUNKY MONKEY BABYS",
    titleMm: "Ato Hitotsu / FUNKY MONKEY BABYS",
    videoId: "bGBy80LdkPI",
    level: "中級",
    subtitles: [
      { start: 13, end: 19, japanese: "あと一粒の涙で ひと言の勇気で", romaji: "ato ichi tsubu no namida de hitokoto no yūki de", myanmar: "မျက်ရည်တစ်စက်ထပ်နဲ့ စကားတစ်ခွန်းရဲ့ ရဲစွမ်းသတ္တိနဲ့" },
      { start: 19, end: 25, japanese: "願いがかなう その時が来るって", romaji: "negai ga kanau sono toki ga kuru tte", myanmar: "ဆုတောင်းချက် ပြည့်မြောက်မည့် အချိန် ရောက်လာမယ်လို့" },
      { start: 25, end: 31, japanese: "僕は信じているから 君もあきらめないでいて", romaji: "boku wa shinji te iru kara kimi mo akirame nai de i te", myanmar: "ငါ ယုံကြည်နေတာမို့ မင်းလည်း လက်မလျှော့နဲ့" },
      { start: 31, end: 50, japanese: "何度でも この両手を あの空へ", romaji: "nan do demo kono ryōte o ano sora e", myanmar: "ဘယ်နှစ်ကြိမ်မဆို ဒီလက်နှစ်ဖက်ကို ထိုမိုးကောင်းကင်ဆီ" },
      { start: 50, end: 53, japanese: "あの日もこんな夏だった", romaji: "ano hi mo konna natsu datsu ta", myanmar: "ထိုနေ့ကလည်း ဒီလို နွေရာသီပဲ" },
      { start: 53, end: 56, japanese: "砂まじりの風が吹いていた", romaji: "suna majiri no kaze ga fui te i ta", myanmar: "သဲပါသောလေ တိုက်ခဲ့တယ်" },
      { start: 56, end: 62, japanese: "グラウンドの真上の空 夕日がまぶしくて", romaji: "guraundo no ma uwanosora yūhi ga mabushiku te", myanmar: "ကွင်းပြင်အပေါ် မိုးကောင်းကင် နေဝင်ချိန် အလွန်တောက်ပတယ်" },
      { start: 62, end: 65, japanese: "どこまで頑張ればいいんだ", romaji: "doko made gambare ba ii n da", myanmar: "ဘယ်လောက်ထိ ကြိုးစားရမှာလဲ" },
      { start: 65, end: 68, japanese: "ぎゅっと唇を噛みしめた", romaji: "gyutto kuchibiru o kamishime ta", myanmar: "နှုတ်ခမ်းကို တင်းကြပ်စွာ ကိုက်မိတယ်" },
      { start: 68, end: 74, japanese: "そんな時 同じ目をした 君に出会ったんだ", romaji: "sonna toki onaji me o shi ta kimi ni deatta n da", myanmar: "ထိုအချိန် တူညီသောမျက်လုံးရှိသော မင်းနဲ့ တွေ့ဆုံခဲ့တယ်" },
      { start: 74, end: 86, japanese: "そう 簡単じゃないからこそ 夢はこんなに輝くんだと", romaji: "sō kantan ja nai kara koso yume wa konnani kagayaku n da to", myanmar: "ဟုတ်တယ် လွယ်မဟုတ်တာကြောင့်ပဲ အိပ်မက်က ဒီလောက် တောက်ပနေတယ်" },
      { start: 86, end: 98, japanese: "そう あの日の君の言葉 今でも胸に抱きしめてるよ", romaji: "sō ano hi no kimi no kotoba ima demo mune ni dakishime teru yo", myanmar: "ဟုတ်တယ် ထိုနေ့ မင်းရဲ့ စကားကို အခုထိ ရင်ခွင်မှာ ဆုပ်ကိုင်ထားတယ်" },
      { start: 98, end: 104, japanese: "あと一粒の涙で ひと言の勇気で", romaji: "ato ichi tsubu no namida de hitokoto no yūki de", myanmar: "မျက်ရည်တစ်စက်ထပ်နဲ့ စကားတစ်ခွန်းရဲ့ ရဲစွမ်းသတ္တိနဲ့" },
      { start: 104, end: 110, japanese: "願いがかなう その時が来るって", romaji: "negai ga kanau sono toki ga kuru tte", myanmar: "ဆုတောင်းချက် ပြည့်မြောက်မည့် အချိန် ရောက်လာမယ်လို့" },
      { start: 110, end: 116, japanese: "僕は信じてるから 君もあきらめないでいて", romaji: "boku wa shinji teru kara kimi mo akirame nai de i te", myanmar: "ငါ ယုံကြည်နေတာမို့ မင်းလည်း လက်မလျှော့နဲ့" },
      { start: 116, end: 121, japanese: "何度でも この両手を", romaji: "nan do demo kono ryōte o", myanmar: "ဘယ်နှစ်ကြိမ်မဆို ဒီလက်နှစ်ဖက်ကို" },
      { start: 121, end: 134, japanese: "あの空へ のばして あの空へ", romaji: "ano sora e nobashi te ano sora e", myanmar: "ထိုမိုးကောင်းကင်ဆီ ဆန့်ကာ ထိုမိုးကောင်းကင်ဆီ" },
      { start: 134, end: 138, japanese: "いつもどうしても素直になれずに", romaji: "itsumo dōshitemo sunao ni nare zu ni", myanmar: "အမြဲ ဘာကြောင့်မှန်းမသိ ရိုးသားစွာမနေနိုင်ဘဲ" },
      { start: 138, end: 141, japanese: "自信なんてまるで持てずに", romaji: "jishin nante marude mote zu ni", myanmar: "ယုံကြည်မှုလည်း လုံးဝမရှိဘဲ" },
      { start: 141, end: 147, japanese: "校舎の裏側 人目を気にして歩いていた", romaji: "kōsha no uragawa hitome o ki ni shi te arui te i ta", myanmar: "ကျောင်းနောက်ဖေး သူများမျက်စိကို သတိထားကာ လျှောက်ခဲ့တယ်" },
      { start: 147, end: 150, japanese: "誰かとぶつかりあうことを", romaji: "dare ka to butsukari au koto o", myanmar: "တစ်ယောက်ယောက်နဲ့ ရင်ဆိုင်တာကို" },
      { start: 150, end: 153, japanese: "心のどこかで遠ざけた", romaji: "kokoro no doko ka de tōzake ta", myanmar: "နှလုံးသားထဲ တစ်နေရာမှာ ဝေးကွာအောင် ထားခဲ့တယ်" },
      { start: 153, end: 156, japanese: "それは本当の自分を", romaji: "sore wa hontō no jibun o", myanmar: "ဒါက တကယ်ကိုယ့်ကိုယ်ကို" },
      { start: 156, end: 160, japanese: "見せるのが怖いだけだったんだと", romaji: "miseru no ga kowai dake datsu ta n da to", myanmar: "ပြဖို့ ကြောက်ရွံ့ရုံသာ ဖြစ်ကြောင်း" },
      { start: 160, end: 164, japanese: "教えてくれたのは", romaji: "oshie te kure ta no wa", myanmar: "သွန်သင်ပေးခဲ့တာ" },
      { start: 164, end: 171, japanese: "君と過ごした今日までの日々", romaji: "kimi to sugoshi ta kyō made no hibi", myanmar: "မင်းနဲ့ ဖြတ်သန်းခဲ့သောနေ့ရက်တွေ ဖြစ်တယ်" },
      { start: 171, end: 176, japanese: "そう初めて口に出来た", romaji: "sō hajimete kuchi ni deki ta", myanmar: "ဟုတ်တယ် ပထမဆုံး ပြောနိုင်ခဲ့တယ်" },
      { start: 176, end: 183, japanese: "泣きたいくらいの本当の夢を", romaji: "naki tai kurai no hontō no yume o", myanmar: "ငိုချင်လောက်သော တကယ့်အိပ်မက်ကို" },
      { start: 183, end: 189, japanese: "あとひとつの坂道を ひとつだけの夜を", romaji: "ato hitotsu no sakamichi o hitotsu dake no yoru o", myanmar: "နောက်တစ်ခု တောင်ကြားလမ်း တစ်ညတည်းသော ညကို" },
      { start: 189, end: 195, japanese: "越えられたなら 笑える日がくるって", romaji: "koe rare ta nara waraeru hi ga kurutte", myanmar: "ကျော်လွန်နိုင်ရင် ရယ်မောနိုင်သောနေ့ ရောက်လာမယ်လို့" },
      { start: 195, end: 202, japanese: "今日も信じてるから 君もあきらめないでいて", romaji: "kyō mo shinji teru kara kimi mo akirame nai de i te", myanmar: "ဒီနေ့လည်း ယုံကြည်နေတာမို့ မင်းလည်း လက်မလျှော့နဲ့" },
      { start: 202, end: 206, japanese: "何度でも この両手を", romaji: "nan do demo kono ryōte o", myanmar: "ဘယ်နှစ်ကြိမ်မဆို ဒီလက်နှစ်ဖက်ကို" },
      { start: 206, end: 219, japanese: "あの空へ", romaji: "ano sora e", myanmar: "ထိုမိုးကောင်းကင်ဆီ" },
      { start: 219, end: 224, japanese: "あつくなっても無駄なんて言葉", romaji: "atsuku natte mo muda nante kotoba", myanmar: "စိတ်အားထက်သန်ရင် အချည်းနှီးဆိုတဲ့ စကား" },
      { start: 224, end: 231, japanese: "聞き飽きたよ もしもそうだとしても", romaji: "kiki aki ta yo moshimo sō da toshite mo", myanmar: "ကြားငြီးပြီ အဲဒီလို ဖြစ်ပါစေ" },
      { start: 231, end: 239, japanese: "抑えきれないこの気持ちを 希望と呼ぶなら", romaji: "osae kire nai kono kimochi o kibō to yobu nara", myanmar: "ထိန်းမနိုင်တဲ့ ဒီစိတ်ကို မျှော်လင့်ချက်လို့ ခေါ်မယ်ဆိုရင်" },
      { start: 239, end: 250, japanese: "いったい 誰が止められると言うのだろう", romaji: "ittai dare ga tome rareru to iu no daro u", myanmar: "တကယ်တော့ ဘယ်သူက တားဆီးနိုင်မယ်လို့ ဆိုကြသလဲ" },
      { start: 250, end: 256, japanese: "あと一粒の涙が あとひと言の勇気が", romaji: "ato ichi tsubu no namida ga ato hitokoto no yūki ga", myanmar: "မျက်ရည်တစ်စက် ရဲစွမ်းသတ္တိ နောက်တစ်ခွန်း" },
      { start: 256, end: 262, japanese: "明日を変えるその時を見たんだ", romaji: "ashita o kaeru sono toki o mi ta n da", myanmar: "မနက်ဖြန်ကို ပြောင်းမည့် အချိန်ကို မြင်ခဲ့တယ်" },
      { start: 262, end: 268, japanese: "なくしかけた光 君が思い出させてくれた", romaji: "nakushi kake ta hikari kimi ga omoidasa se te kure ta", myanmar: "ဆုံးရှုံးတော့မည့် အလင်းကို မင်းက သတိရစေခဲ့တယ်" },
      { start: 268, end: 274, japanese: "あの日の景色 忘れない", romaji: "ano hi no keshiki wasure nai", myanmar: "ထိုနေ့ မြင်ကွင်းကို မမေ့နိုင်ဘူး" },
      { start: 274, end: 281, japanese: "あと一粒の涙で ひと言の勇気で", romaji: "ato ichi tsubu no namida de hitokoto no yūki de", myanmar: "မျက်ရည်တစ်စက်ထပ်နဲ့ ရဲစွမ်းသတ္တိတစ်ခွန်းနဲ့" },
      { start: 281, end: 286, japanese: "願いがかなう その時が来るって", romaji: "negai ga kanau sono toki ga kuru tte", myanmar: "ဆုတောင်းချက် ပြည့်မြောက်မည့် အချိန် ရောက်လာမယ်လို့" },
      { start: 286, end: 293, japanese: "僕は信じてるから 君もあきらめないでいて", romaji: "boku wa shinji teru kara kimi mo akirame nai de i te", myanmar: "ငါ ယုံကြည်နေတာမို့ မင်းလည်း လက်မလျှော့နဲ့" },
      { start: 293, end: 298, japanese: "何度でも この両手を", romaji: "nan do demo kono ryōte o", myanmar: "ဘယ်နှစ်ကြိမ်မဆို ဒီလက်နှစ်ဖက်ကို" },
      { start: 298, end: 999, japanese: "あの空へ のばして あの空へ", romaji: "ano sora e nobashi te ano sora e", myanmar: "ထိုမိုးကောင်းကင်ဆီ ဆန့်ကာ ထိုမိုးကောင်းကင်ဆီ" },
    ],
  },
  {
    id: "2",
    title: "secret base〜君がくれたもの〜 / ZONE",
    titleMm: "secret base / ZONE",
    videoId: "ACo60qnd_Lc",
    level: "中級",
    subtitles: [
      { start: 14, end: 18, japanese: "君と夏の終わり 将来の夢", romaji: "kimi to natsu no owari shōrai no yume", myanmar: "မင်းနဲ့ နွေရာသီကုန်ချိန် အနာဂတ်အိပ်မက်" },
      { start: 18, end: 22, japanese: "大きな希望 忘れない", romaji: "ōkina kibō wasure nai", myanmar: "မြော်လင့်ချက်ကြီး မမေ့နိုင်ဘူး" },
      { start: 22, end: 24, japanese: "10年後の8月", romaji: "10 nen go no 8 tsuki", myanmar: "၁၀ နှစ်နောက် သြဂုတ်လမှာ" },
      { start: 24, end: 29, japanese: "また出会えるの 信じて", romaji: "mata deaeru no shinji te", myanmar: "တစ်ဖန်တွေ့နိုင်မယ်လို့ ယုံကြည်တယ်" },
      { start: 54, end: 61, japanese: "出会いはふっとした瞬間 帰り道の交差点で", romaji: "deai wa futto shi ta shunkan kaerimichi no kōsaten de", myanmar: "တွေ့ဆုံမှုက မမျှော်ထားသောအချိန် အပြန်လမ်း လမ်းဆုံမှာ" },
      { start: 61, end: 68, japanese: "声をかけてくれたね 「一緒に帰ろう」", romaji: "koe o kake te kure ta ne issho ni kaerō", myanmar: "ခေါ်ဆိုပေးခဲ့တယ် 'အတူတူ ပြန်ကြရအောင်'" },
      { start: 68, end: 76, japanese: "僕は照れくさそうに カバンで顔を隠しながら", romaji: "boku wa terekusa sō ni kaban de kao o kakushi nagara", myanmar: "ကျွန်တော် ရှက်ရွံ့ဟန်နဲ့ အိတ်နဲ့မျက်နှာဖုံးရင်း" },
      { start: 76, end: 83, japanese: "本当はとてもとても 嬉しかったよ", romaji: "hontōwa totemo totemo ureshikatta yo", myanmar: "တကယ်တော့ အရမ်းအရမ်း ဝမ်းသာခဲ့တယ်" },
      { start: 83, end: 90, japanese: "あぁ花火が夜空きれいに咲いて ちょっとセツナク", romaji: "ā hanabi ga yozora kirei ni sai te chotto setsunaku", myanmar: "အင်း မီးပန်းပွင့်တွေ ညအကောင်းမှာ လှပစွာပွင့်ကာ နည်းနည်းဝမ်းနည်းမိတယ်" },
      { start: 90, end: 97, japanese: "あぁ 風が時間とともに 流れる", romaji: "ā kaze ga jikan totomoni nagareru", myanmar: "အင်း လေက အချိန်နဲ့အတူ စီးဆင်းသွားတယ်" },
      { start: 97, end: 104, japanese: "嬉しくって楽しくって 冒険もいろいろしたね", romaji: "ureshikutte tanoshikutte bōken mo iroiro shi ta ne", myanmar: "ဝမ်းသာပြီး ပျော်ရွင်ကာ စွန့်စားမှုများစွာ လုပ်ခဲ့တယ်နော်" },
      { start: 104, end: 112, japanese: "二人の 秘密の基地の中", romaji: "ni nin no himitsu no kichi no naka", myanmar: "နှစ်ယောက်တည်း လျှို့ဝှက်ဌာနချိုထဲမှာ" },
      { start: 112, end: 125, japanese: "君と夏の終わり 将来の夢 大きな希望忘れない", romaji: "kimi to natsu no owari shōrai no yume ōkina kibō wasure nai", myanmar: "မင်းနဲ့ နွေရာသီကုန်ချိန် အနာဂတ်အိပ်မက် မြော်လင့်ချက်ကြီး မမေ့နိုင်ဘူး" },
      { start: 125, end: 133, japanese: "君が最後まで 心から「ありがとう」", romaji: "kimi ga saigo made kokorokara arigatō", myanmar: "မင်း နောက်ဆုံးထိ နှလုံးသားဆိုင်ရာ 'ကျေးဇူးတင်တယ်'" },
      { start: 133, end: 140, japanese: "叫んでいたこと 知っていたよ", romaji: "saken de i ta koto shitte i ta yo", myanmar: "အော်ဟစ်နေသည်ကို သိနေခဲ့တယ်" },
      { start: 140, end: 147, japanese: "涙をこらえて 笑顔でさよなら せつないよね", romaji: "namida o korae te egao de sayonara setsunai yo ne", myanmar: "မျက်ရည်တန့်ကာ အပြုံးနဲ့ နှုတ်ဆက်ခဲ့တယ် ဝမ်းနည်းစရာကောင်းတယ်နော်" },
      { start: 155, end: 163, japanese: "あぁ夏休みもあと少しで 終わっちゃうから", romaji: "ā natsuyasumi mo ato sukoshi de owatchau kara", myanmar: "အင်း နွေရာသီပိတ်ရက်လည်း နည်းနည်းနဲ့ ကုန်တော့မယ်မို့" },
      { start: 170, end: 178, japanese: "悲しくって寂しくって 喧嘩もいろいろしたね", romaji: "kanashikutte sabishikutte kenka mo iroiro shi ta ne", myanmar: "ဝမ်းနည်းပြီး တမ်းတကာ ရန်ဖြစ်မှုများစွာလည်း ရှိခဲ့တယ်နော်" },
      { start: 178, end: 186, japanese: "二人の 秘密の基地の中", romaji: "ni nin no himitsu no kichi no naka", myanmar: "နှစ်ယောက်တည်း လျှို့ဝှက်ဌာနချိုထဲမှာ" },
      { start: 197, end: 213, japanese: "涙をこらえて 笑顔でさよなら せつないよね", romaji: "namida o korae te egao de sayonara setsunai yo ne", myanmar: "မျက်ရည်တန့်ကာ အပြုံးနဲ့ နှုတ်ဆက်တယ် ဝမ်းနည်းစရာ" },
      { start: 219, end: 232, japanese: "手紙書くよ電話もするよ 忘れないでね僕のことを", romaji: "tegami kaku yo denwa mo suru yo wasure nai de ne boku no koto o", myanmar: "စာရေးမယ် ဖုန်းလည်း ဆက်မယ် ကျွန်တော့်ကို မမေ့နဲ့နော်" },
      { start: 232, end: 240, japanese: "いつまでも 二人の 基地の中", romaji: "itsu made mo ni nin no kichi no naka", myanmar: "အမြဲတမ်း နှစ်ယောက်တည်း ဌာနချိုထဲမှာ" },
      { start: 240, end: 252, japanese: "君と夏の終わり ずっと話して 夕日を見てから星を眺め", romaji: "kimi to natsu no owari zutto hanashi te yūhi o mi te kara hoshi o nagame", myanmar: "မင်းနဲ့ နွေကုန်ချိန် အမြဲစကားပြောကာ နေဝင်ကြည့်ပြီး ကြယ်တွေ ငေးကြည့်တယ်" },
      { start: 252, end: 262, japanese: "君の頬を 流れた涙は ずっと忘れない", romaji: "kimi no hō o nagare ta namida wa zutto wasure nai", myanmar: "မင်းပါးပေါ် စီးဆင်းသောမျက်ရည် အမြဲမမေ့နိုင်ဘူး" },
      { start: 247, end: 256, japanese: "君が最後まで 大きく手を振ってくれたこと きっと忘れない", romaji: "kimi ga saigo made ōkiku te o futte kure ta koto kitto wasure nai", myanmar: "မင်း နောက်ဆုံးထိ လက်ကြီးကြီး လှုပ်ပေးခဲ့တာ ဧကန်မမေ့နိုင်ဘူး" },
      { start: 262, end: 275, japanese: "だからこうして 夢の中でずっと永遠に…", romaji: "dakara kōshite yume no naka de zutto eien ni", myanmar: "ဒါကြောင့် ဒီလို အိပ်မက်ထဲမှာ အမြဲထာဝရ..." },
      { start: 281, end: 295, japanese: "10年後の8月 また出会えるの信じて", romaji: "10 nen go no 8 tsuki mata deaeru no shinji te", myanmar: "၁၀ နှစ်နောက် သြဂုတ်လမှာ တစ်ဖန်တွေ့မယ်လို့ ယုံကြည်တယ်" },
      { start: 295, end: 999, japanese: "涙をこらえて 笑顔でさよなら せつないよね 最高の思い出を…", romaji: "namida o korae te egao de sayonara setsunai yo ne saikō no omoide o", myanmar: "မျက်ရည်တန့်ကာ အပြုံးနဲ့ နှုတ်ဆက်တယ် ဝမ်းနည်းစရာ... အကောင်းဆုံးသောမှတ်ဉာဏ်..." },
    ],
  },
  {
    id: "3",
    title: "夜に駆ける / YOASOBI",
    titleMm: "Yoru ni Kakeru / YOASOBI",
    videoId: "l1QxlhkmFlg",
    level: "中級",
    subtitles: [
      { start: 1, end: 6, japanese: "沈むように溶けてゆくように", romaji: "shizumu yō ni toke te yuku yō ni", myanmar: "နစ်မြုပ်ပြီး အရည်ပျော်သွားသလိုပဲ။" },
      { start: 8, end: 14, japanese: "二人だけの空が広がる夜に", romaji: "ni nin ta keno sora ka  hiro ka ru yoru ni", myanmar: "ကောင်းကင်က ငါတို့နှစ်ယောက်တည်းရှိတဲ့ ညတစ်ညမှာ" },
      { start: 31, end: 33, japanese: "「さよなら」だけだった", romaji: "sayonara ta ketatta", myanmar: "ငါပြောသမျှ 'နှုတ်ဆက်ပါတယ်'" },
      { start: 33, end: 37, japanese: "その一言で全てが分かった", romaji: "sono hitokoto te  subete ka  wakatta", myanmar: "ဒီစကားတစ်ခွန်းနဲ့ အရာအားလုံးကို နားလည်ခဲ့တယ်။" },
      { start: 37, end: 41, japanese: "日が沈み出した空と君の姿", romaji: "hi ka  shizumi dashi ta sora to kimi no sugata", myanmar: "နေဝင်သည်နှင့်အမျှ ကောင်းကင်နှင့် မင်း" },
      { start: 41, end: 46, japanese: "フェンス越しに重なっていた", romaji: "fensu goshi ni kasanatte i ta", myanmar: "ခြံစည်းရိုးပေါ်မှာ ထပ်နေခဲ့တယ်။" },
      { start: 46, end: 48, japanese: "初めて会った日から", romaji: "hajimete atta hi kara", myanmar: "ပထမဆုံးစတွေ့တဲ့နေ့ကစပြီး" },
      { start: 48, end: 52, japanese: "僕の心の全てを奪った", romaji: "boku no kokoro no subete o ubatta", myanmar: "ငါ့နှလုံးသားတစ်ခုလုံးကို ခိုးယူသွားတယ်။" },
      { start: 52, end: 56, japanese: "どこか儚い空気を纏う君は", romaji: "to koka hakanai kūki o matou kimi wa", myanmar: "မင်းဟာ တခဏတာ လေထဲမှာ ဝိုင်းရံနေတယ်။" },
      { start: 56, end: 60, japanese: "寂しい目をしてたんだ", romaji: "sabishii me o shi te tan ta ", myanmar: "အထီးကျန်တဲ့ မျက်လုံးတွေ ရှိခဲ့တယ်။" },
      { start: 60, end: 62, japanese: "いつだってチックタックと", romaji: "i tsu ta tte chikku takku to", myanmar: "အမြဲတမ်း Tic Tac" },
      { start: 62, end: 63, japanese: "鳴る世界で何度だってさ", romaji: "naru sekai te  nan do ta ttesa", myanmar: "ကမ္ဘာမှာ ဘယ်နှစ်ခါပဲ မြည်နေပါစေ။" },
      { start: 63, end: 65, japanese: "触れる心無い言葉", romaji: "fureru kokoronai kotoba", myanmar: "ငါ့ကိုမထိတဲ့စကားတွေ" },
      { start: 65, end: 66, japanese: "うるさい声に", romaji: "urusai koe ni", myanmar: "ဆူညံသောအသံဆီသို့" },
      { start: 66, end: 68, japanese: "涙が零れそうでも", romaji: "namida ka  kobore sō te mo", myanmar: "မျက်​ရည်​​တောင်​ကျ​တော့မည်​" },
      { start: 68, end: 74, japanese: "ありきたりな喜びきっと二人なら見つけられる", romaji: "ari ki tari na ki hi kitto ni nin nara mitsuke rareru", myanmar: "ငါတို့နှစ်ယောက် သာမာန်ပျော်ရွှင်မှုကို ရှာတွေ့နိုင်မယ်ဆိုတာ ငါသေချာပါတယ်။" },
      { start: 74, end: 78, japanese: "騒がしい日々に笑えない君に", romaji: "騒 ka shii hibi ni warae nai kimi ni", myanmar: "ဆူညံသောနေ့များတွင် မပြုံးနိုင်သော မင်းအတွက်" },
      { start: 78, end: 82, japanese: "思い付く限り眩しい明日を", romaji: "omoitsuku kagiri mabushii ashita o", myanmar: "အတောက်ပဆုံးမနက်ဖြန်ဆိုတာ ငါတွေးလို့ရတယ်။" },
      { start: 82, end: 86, japanese: "明けない夜に落ちてゆく前に", romaji: "ake nai yoru ni ochi te yuku mae ni", myanmar: "အဆုံးမရှိသောညသို့ မကျရောက်မီ" },
      { start: 86, end: 89, japanese: "僕の手を掴んでほら", romaji: "boku no te o tsukan te hora", myanmar: "ငါ့လက်ကိုယူ၊ လာလော့" },
      { start: 89, end: 93, japanese: "忘れてしまいたくて閉じ込めた日々も", romaji: "wasure te shimai taku te tozashi  kome ta hibi mo", myanmar: "မေ့ပစ်ချင်တာကြောင့် သော့ခတ်ထားတဲ့ နေ့ရက်တွေပါ။" },
      { start: 93, end: 97, japanese: "抱きしめた温もりで溶かすから", romaji: "dakishime ta nukumori te  tokasu kara", myanmar: "မင်းရဲ့ရင်ခွင်က နွေးထွေးမှုတွေနဲ့ ငါ အရည်ပျော်သွားလိမ့်မယ်။" },
      { start: 97, end: 101, japanese: "怖くないよ いつか日が昇るまで", romaji: "kowaku nai yo itsuka nichi ka  noboru mate ", myanmar: "တစ်နေ့နေ့ နေထွက်တဲ့အထိ မကြောက်ပါဘူး။" },
      { start: 101, end: 103, japanese: "二人でいよう", romaji: "ni nin te iyou", myanmar: "အတူရှိကြပါစို့" },
      { start: 118, end: 120, japanese: "君にしか見えない", romaji: "kimi ni shika mie nai", myanmar: "သင်သာမြင်နိုင်သည်။" },
      { start: 120, end: 124, japanese: "何かを見つめる君が嫌いだ", romaji: "nani ka o mitsumeru kimi ka  kirai ta ", myanmar: "တစ်ခုခုကို စိုက်ကြည့်တဲ့အခါ မုန်းတယ်။" },
      { start: 124, end: 126, japanese: "見惚れているかのような", romaji: "mihore te iru ka no yō na", myanmar: "ငါမင်းကိုချစ်နေသလိုပဲ။" },
      { start: 126, end: 128, japanese: "恋するような", romaji: "koisuru yō na", myanmar: "ချစ်မိသွားသလိုပါပဲ။" },
      { start: 128, end: 131, japanese: "そんな顔が嫌いだ", romaji: "sonna kao ka  kirai ta ", myanmar: "အဲဒီမျက်နှာကို မုန်းတယ်။" },
      { start: 132, end: 134, japanese: "信じていたいけど信じれないこと", romaji: "shin shi teitaiketo shin shi renaikoto", myanmar: "ယုံချင်ပေမယ့် မယုံနိုင်တဲ့အရာ" },
      { start: 134, end: 135, japanese: "そんなのどうしたってきっと", romaji: "sonna no to ushitattekitto", myanmar: "အဲဒါဘာဖြစ်နေတာလဲ သေချာတယ်။" },
      { start: 135, end: 137, japanese: "これからだっていくつもあって", romaji: "korekara ta tteikutsumoatte", myanmar: "အခုချိန်ကစပြီး အများကြီးရှိမယ်။" },
      { start: 137, end: 139, japanese: "そのたんび怒って泣いていくの", romaji: "sono tan hi  okotte nai te iku no", myanmar: "အဲဒီလိုလုပ်လိုက်တာနဲ့ ဒေါသထွက်ပြီး ငိုတယ်။" },
      { start: 139, end: 140, japanese: "それでもきっと", romaji: "sore te mokitto", myanmar: "ဒါတောင် သေချာပါတယ်။" },
      { start: 140, end: 141, japanese: "いつかはきっと", romaji: "itsuka wa kitto", myanmar: "တစ်နေ့နေ့တော့ သေချာပါတယ်။" },
      { start: 141, end: 142, japanese: "僕らはきっと", romaji: "bokura wa kitto", myanmar: "ကျွန်တော်သေချာပါတယ်။" },
      { start: 142, end: 144, japanese: "分かり合えるさ信じてるよ", romaji: "wakari aeru sa shin shi teruyo", myanmar: "တစ်ယောက်နဲ့တစ်ယောက် နားလည်နိုင်မယ်လို့ ယုံကြည်ပါတယ်။" },
      { start: 144, end: 146, japanese: "信じてるよ", romaji: "shin shi teruyo", myanmar: "ယုံတယ်။" },
      { start: 161, end: 163, japanese: "もう嫌だって疲れたんだって", romaji: "mō iya ta tte tsukare ta n ta tte", myanmar: "မကြိုက်တော့ဘူး၊ ပင်ပန်းတယ်။" },
      { start: 163, end: 165, japanese: "がむしゃらに差し伸べた", romaji: "ka musharani sashi shin e ta", myanmar: "အသဲအသန် ဆုပ်ကိုင်လိုက်မိတယ်။" },
      { start: 165, end: 167, japanese: "僕の手を振り払う君", romaji: "boku no te o furiharau kimi", myanmar: "မင်းငါ့လက်ကို ဖယ်လိုက်" },
      { start: 167, end: 170, japanese: "もう嫌だって疲れたよなんて", romaji: "mō iya ta tte tsukare ta yo nante", myanmar: "မလိုချင်တော့ဘူး၊ ပင်ပန်းတယ်။" },
      { start: 170, end: 174, japanese: "本当は僕も言いたいんだ", romaji: "hontōwa boku mo ii tai n ta ", myanmar: "အမှန်တော့ ကျွန်တော်လည်း ပြောချင်တယ်။" },
      { start: 175, end: 176, japanese: "ほらまたチックタックと", romaji: "hora mata chikku takku to", myanmar: "Tic Tac ပြန်ကြည့်" },
      { start: 176, end: 178, japanese: "鳴る世界で何度だってさ", romaji: "naru sekai te  nan do ta ttesa", myanmar: "ကမ္ဘာမှာ ဘယ်နှစ်ခါပဲ မြည်နေပါစေ။" },
      { start: 178, end: 180, japanese: "君の為に用意した言葉", romaji: "kimi no tame ni yōi shi ta kotoba", myanmar: "သင့်အတွက် ပြင်ဆင်ထားသော စကားလုံးများ" },
      { start: 180, end: 181, japanese: "どれも届かない", romaji: "to remo todoke ka nai", myanmar: "တစ်ယောက်မှ မရောက်ဘူး။" },
      { start: 181, end: 183, japanese: "「終わりにしたい」だなんてさ", romaji: "owari ni shi tai ta nantesa", myanmar: "'ငါ အဲဒါကို အဆုံးသတ်ချင်တယ်' တဲ့။" },
      { start: 183, end: 185, japanese: "釣られて言葉にした時", romaji: "tsura re te kotoba ni shi ta toki", myanmar: "စကားလုံးတွေနဲ့ ဆွဲဆောင်ခံရတဲ့အခါ" },
      { start: 185, end: 189, japanese: "君は初めて笑った", romaji: "kimi wa hajimete waratta", myanmar: "မင်းပထမဆုံးအကြိမ်ရယ်" },
      { start: 191, end: 195, japanese: "騒がしい日々に笑えなくなっていた", romaji: "騒 ka shii hibi ni warae naku natte i ta", myanmar: "မင်းမျက်လုံးတွေကို ကြည့်လိုက်တော့ မင်းကို တင်းတင်းကြပ်ကြပ် ဖက်ထားလိုက်တယ်။" },
      { start: 195, end: 198, japanese: "僕の目に映る君は綺麗だ", romaji: "boku no me ni utsuru kimi wa kirei ta ", myanmar: "မင်းက ငါ့မျက်လုံးထဲမှာ လှတယ်။" },
      { start: 198, end: 202, japanese: "明けない夜に溢れた涙も", romaji: "ake nai yoru ni afure ta namida mo", myanmar: "အဆုံးမရှိသောည၌ မျက်ရည်များစီးကျလာသည်။" },
      { start: 202, end: 206, japanese: "君の笑顔に溶けていく", romaji: "kimi no egao ni toke te iku", myanmar: "မင်းရဲ့အပြုံးကြောင့် ငါပျော်နေတယ်။" },
      { start: 207, end: 211, japanese: "変わらない日々に泣いていた僕を", romaji: "kawara nai hibi ni nai te i ta boku o", myanmar: "မပြောင်းလဲတဲ့နေ့တွေမှာ ငိုခဲ့တယ်။" },
      { start: 211, end: 215, japanese: "君は優しく終わりへと誘う", romaji: "kimi wa yasashiku owari e to sasou", myanmar: "မင်းငါ့ကို အဆုံးထိ ညင်သာစွာ ဖိတ်ခေါ်တယ်။" },
      { start: 215, end: 219, japanese: "沈むように溶けてゆくように", romaji: "shizumu yō ni toke te yuku yō ni", myanmar: "နစ်မြုပ်ပြီး အရည်ပျော်သွားသလိုပဲ။" },
      { start: 219, end: 222, japanese: "染み付いた霧が晴れる", romaji: "shimitsui ta kiri ka  hareru", myanmar: "မြူခိုးများက ရှင်းနေသည်။" },
      { start: 222, end: 226, japanese: "忘れてしまいたくて閉じ込めた日々に", romaji: "wasure te shimai taku te tozashi  kome ta hibi ni", myanmar: "မေ့ပစ်ချင်တာကြောင့် သော့ခတ်ထားတဲ့ နေ့ရက်တွေပေါ့။" },
      { start: 226, end: 230, japanese: "差し伸べてくれた君の手を取る", romaji: "sashi shin e tekureta kun no te o toru", myanmar: "မင်းလက်ကို ငါကိုင်လိုက်မယ်။" },
      { start: 230, end: 235, japanese: "涼しい風が空を泳ぐように今", romaji: "suzushii kaze ka  sora o 泳 ku youni ima", myanmar: "အခု ကောင်းကင်မှာ အေးမြတဲ့ လေနုအေးတွေ ကူးခတ်နေသလိုပဲ။" },
      { start: 235, end: 237, japanese: "吹き抜けていく", romaji: "fukinuke te iku", myanmar: "မှုတ်" },
      { start: 237, end: 240, japanese: "繋いだ手を離さないでよ", romaji: "tsunai ta  shu o hanasa nai te yo", myanmar: "ငါတို့ရဲ့ ချိတ်ဆက်ထားတဲ့ လက်တွေကို မလွှတ်လိုက်ပါနဲ့။" },
      { start: 240, end: 243, japanese: "二人今、夜に駆け出していく", romaji: "ni nin ima yoru ni kakedashi te iku", myanmar: "ကျွန်တော်တို့ နှစ်ယောက် ညဘက်ဆို ပြေးနေကြပြီ။" },
      { start: 258, end: 262, japanese: "Thanks for watching!", romaji: "Thanks for watching !", myanmar: "ကြည့်ရှုမှုအတွက် ကျေးဇူးတင်ပါသည်။" },
    ],
  },
  {
    id: "4",
    title: "Lemon / 米津玄師",
    titleMm: "Lemon / Kenshi Yonezu",
    videoId: "MxjXe5eg6vY",
    level: "中級",
    subtitles: [
      { start: 2, end: 7, japanese: "夢ならばどれほどよかったでしょう", romaji: "yume nara wa torehotoyokattateshou", myanmar: "အိပ်မက်ဖြစ်ရင် ဘယ်လောက်ကောင်းမလဲ။" },
      { start: 8, end: 13, japanese: "未だにあなたのことを夢にみる", romaji: "mi ta nianatanokotoo yume ni miru", myanmar: "ငါ မင်းအကြောင်း အိပ်မက်မက်နေတုန်းပဲ။" },
      { start: 13, end: 18, japanese: "忘れた物を取りに帰るように", romaji: "wasure ta mono o tori ni kaeru yō ni", myanmar: "အိမ်ပြန်ရတာ မေ့သွားသလိုပါပဲ။" },
      { start: 18, end: 24, japanese: "古びた思い出の埃を払う", romaji: "ko hi ta omoide no hokori o harau", myanmar: "အမှတ်​တရ​ဟောင်း​တွေကို ဖယ်​လိုက်​ပါ။" },
      { start: 27, end: 32, japanese: "戻らない幸せがあることを", romaji: "modora nai shiawase ka arukotoo", myanmar: "ဘယ်တော့မှ ပြန်မရနိုင်တဲ့ ပျော်ရွှင်မှုတွေ ရှိနေတယ်။" },
      { start: 32, end: 38, japanese: "最後にあなたが教えてくれた", romaji: "saigo ni anata ka  oshie te kure ta", myanmar: "နောက်ဆုံးတော့ မင်းငါ့ကိုပြောတယ်။" },
      { start: 38, end: 43, japanese: "言えずに隠してた昏い過去も", romaji: "ie su ni kakushi te ta 昏 i kako mo", myanmar: "ပြောမပြနိုင်ဘဲ ဖုံးကွယ်ထားတဲ့ မှောင်မိုက်တဲ့အတိတ်" },
      { start: 44, end: 49, japanese: "あなたがいなきゃ永遠に昏いまま", romaji: "anata ka inakya eien ni 昏 ima ma", myanmar: "မင်းမရှိရင် ငါအမှောင်ထဲမှာ ထာဝရရှိနေမယ်။" },
      { start: 49, end: 52, japanese: "きっともうこれ以上", romaji: "kitto mō kore ijō", myanmar: "ဒီ့ထက် ပိုသေချာပါတယ်။" },
      { start: 52, end: 55, japanese: "傷つくことなど", romaji: "kizutsuku koto na to ", myanmar: "ထိခိုက်ခြင်းစသည်တို့" },
      { start: 55, end: 60, japanese: "ありはしないとわかっている", romaji: "ari wa shi nai to wakatte iru", myanmar: "ဖြစ်မလာဘူးဆိုတာ ငါသိတယ်။" },
      { start: 60, end: 65, japanese: "あの日の悲しみさえ あの日の苦しみさえ", romaji: "ano hi no kanashimi sae ano hi no kurushimi sae", myanmar: "ထိုနေ့၏ ဝမ်းနည်းမှုပင်၊ ထိုနေ့၏ ဝေဒနာပင်" },
      { start: 65, end: 71, japanese: "そのすべてを愛してた あなたとともに", romaji: "sono su e teo aishi te ta anata totomoni", myanmar: "မင်းနဲ့အတူ အားလုံးကို ငါချစ်တယ်။" },
      { start: 71, end: 76, japanese: "胸に残り離れない 苦いレモンの匂い", romaji: "mune ni nokori hanare nai nigai remon no nioi", myanmar: "ခါးသီးတဲ့ သံပုရာသီးရနံ့က ငါ့ရင်ထဲမှာ စွဲမြဲနေတယ်။" },
      { start: 77, end: 82, japanese: "雨が降り止むまでは帰れない", romaji: "ame ka  ori tome mumateha kaere nai", myanmar: "မိုးတိတ်တဲ့အထိ အိမ်မပြန်နိုင်ဘူး။" },
      { start: 82, end: 88, japanese: "今でもあなたはわたしの光", romaji: "ima te moanatahawatashino kō", myanmar: "မင်းဟာ ငါ့ရဲ့အလင်းဖြစ်နေတုန်းပဲ။" },
      { start: 99, end: 104, japanese: "暗闇であなたの背をなぞった", romaji: "kurayami te anatano se o naso tta", myanmar: "အမှောင်ထဲမှာ မင်းရဲ့နောက်ကြောင်းကို ငါခြေရာခံခဲ့တယ်။" },
      { start: 104, end: 110, japanese: "その輪郭を鮮明に覚えている", romaji: "sono rinkaku o semmei ni oboe te iru", myanmar: "သူ့ရဲ့ ကောက်ကြောင်းကို ရှင်းရှင်းလင်းလင်း မှတ်မိနေတယ်။" },
      { start: 110, end: 115, japanese: "受け止めきれないものと出会うたび", romaji: "uketome kire nai mono to deau ta hi ", myanmar: "ငါလက်မခံနိုင်တဲ့အရာတစ်ခုကြုံတိုင်း" },
      { start: 115, end: 121, japanese: "溢れてやまないのは涙だけ", romaji: "afure te yama nai no wa namida ta ke", myanmar: "တားမရသော တစ်ခုတည်းသော အရာမှာ မျက်ရည်များပင်" },
      { start: 121, end: 127, japanese: "何をしていたの 何を見ていたの", romaji: "nani o shi te i ta no nani o mi te i ta no", myanmar: "မင်းဘာလုပ်နေတာလဲ။ မင်းဘာကြည့်နေတာလဲ" },
      { start: 127, end: 131, japanese: "わたしの知らない横顔で", romaji: "watashi no shira nai yokogao te ", myanmar: "ကိုယ်မသိတဲ့ profile နဲ့" },
      { start: 131, end: 137, japanese: "どこかであなたが今 わたしと同じ様な", romaji: "to kokateanataka ima watashi to dō shi  sama na", myanmar: "တစ်နေရာရာမှာ မင်းက အခုငါနဲ့တူတယ်။" },
      { start: 137, end: 142, japanese: "涙にくれ 淋しさの中にいるなら", romaji: "namida ni kure sabishi sa no naka ni iru nara", myanmar: "မျက်ရည်ကျရင် အထီးကျန်ဆန်တယ်။" },
      { start: 142, end: 148, japanese: "わたしのことなどどうか 忘れてください", romaji: "watashi no koto na to touka wasure te ku ta sai", myanmar: "ကျေးဇူးပြုပြီး ငါ့ကိုမေ့လိုက်ပါ။" },
      { start: 148, end: 154, japanese: "そんなことを心から願うほどに", romaji: "sonna koto o kokorokara negau ho to ni", myanmar: "အဲဒါကို ပိုလို့ စိတ်ရင်းမှန်နဲ့ လိုချင်တယ်။" },
      { start: 154, end: 159, japanese: "今でもあなたはわたしの光", romaji: "ima te moanatahawatashino kō", myanmar: "မင်းဟာ ငါ့ရဲ့အလင်းဖြစ်နေတုန်းပဲ။" },
      { start: 163, end: 168, japanese: "自分が思うより", romaji: "jibun ka  omou yori", myanmar: "ငါထင်ထားတာထက်" },
      { start: 168, end: 173, japanese: "恋をしていたあなたに", romaji: "koi o shi te i ta anata ni", myanmar: "ချစ်ခဲ့ဖူးသောမင်းအတွက်" },
      { start: 174, end: 179, japanese: "あれから思うように", romaji: "are kara omou yō ni", myanmar: "အဲ့ကတည်းက ငါထင်ခဲ့တာ" },
      { start: 179, end: 184, japanese: "息ができない", romaji: "iki ka tekinai", myanmar: "ငါအသက်မရှူနိုင်ဘူး။" },
      { start: 184, end: 190, japanese: "あんなに側にいたのに", romaji: "annani gawa ni i ta noni", myanmar: "မင်းအနားမှာ ငါဒီလိုရှိနေပေမယ့်" },
      { start: 190, end: 195, japanese: "まるで嘘みたい", romaji: "maru te  uso mitai", myanmar: "လိမ်သလိုပါပဲ။" },
      { start: 195, end: 201, japanese: "とても忘れられない", romaji: "totemo wasure rare nai", myanmar: "မမေ့နိုင်စရာ" },
      { start: 201, end: 209, japanese: "それだけが確か", romaji: "sore ta keka tashika", myanmar: "ဒါပဲသေချာတယ်။" },
      { start: 212, end: 214, japanese: "あの日の悲しみさえ", romaji: "ano hi no kanashimi sae", myanmar: "ထိုနေ့က ဝမ်းနည်းစရာပင်" },
      { start: 214, end: 217, japanese: "あの日の苦しみさえ", romaji: "ano hi no kurushimi sae", myanmar: "ထိုနေ့၏ ဝေဒနာပင်" },
      { start: 217, end: 220, japanese: "そのすべてを愛してた", romaji: "sono su e teo aishi te ta", myanmar: "အားလုံးကို ချစ်တယ်။" },
      { start: 220, end: 223, japanese: "あなたとともに", romaji: "anata totomoni", myanmar: "သင့်နှင့်အတူ" },
      { start: 223, end: 228, japanese: "胸に残り離れない 苦いレモンの匂い", romaji: "mune ni nokori hanare nai nigai remon no nioi", myanmar: "ခါးသီးတဲ့ သံပုရာသီးရနံ့က ငါ့ရင်ထဲမှာ စွဲမြဲနေတယ်။" },
      { start: 228, end: 234, japanese: "雨が降り止むまでは帰れない", romaji: "ame ka  ori tome mumateha kaere nai", myanmar: "မိုးတိတ်တဲ့အထိ အိမ်မပြန်နိုင်ဘူး။" },
      { start: 234, end: 239, japanese: "切り分けた果実の片方の様に", romaji: "kiriwake ta kajitsu no katahō no yō ni", myanmar: "လှီးဖြတ်ထားသော အသီးတစ်ဝက်ကဲ့သို့ပင်" },
      { start: 239, end: 246, japanese: "今でもあなたはわたしの光", romaji: "ima te moanatahawatashino kō", myanmar: "မင်းဟာ ငါ့ရဲ့အလင်းဖြစ်နေတုန်းပဲ။" },
      { start: 253, end: 255, japanese: "Thanks for watching!!", romaji: "Thanks for watching !!", myanmar: "ကြည့်ရှုမှုအတွက် ကျေးဇူးတင်ပါတယ်!!" },
    ],
  },
  {
    id: "5",
    title: "Pretender / Official髭男dism",
    titleMm: "Pretender / Official HIGE DANdism",
    videoId: "TnrVt--rXHY",
    level: "上級",
    subtitles: [
      { start: 23, end: 39, japanese: "君とのラブストーリー それは予想通り いざ始まればひとり芝居だ ずっとそばにいたって 結局ただの観客だ", romaji: "kimi to no rabusutōrī sore wa yosō dōri iza hajimare ba hitori shibai da zutto soba ni itatte kekkyoku tada no kankyaku da", myanmar: "မင်းနဲ့ငါ့ရဲ့အချစ်ဇာတ်လမ်းက အစကတည်းက ငါမျှော်လင့်ထားသလိုပဲ၊ မင်းရဲ့ဘေးမှာတစ်ချိန်လုံးရှိနေတယ်ဆိုတောင်မှ ငါက ပရိသတ်တစ်ယောက်ပဲလေ။" },
      { start: 39, end: 58, japanese: "感情のないアイムソーリー それはいつも通り 慣れてしまえば悪くはないけど 君とのロマンスは人生柄 続きはしないことを知った", romaji: "kanjō no nai aimusōrī sore wa itsumo tōri nare te shimae ba waruku wa nai kedo kimi to no romansu wa jinsei gara tsuzuki wa shi nai koto o shitta", myanmar: "ခံစားချက်မရှိရင် တောင်းပန်ပါတယ် အဲဒါအမြဲတမ်း အတူတူပါပဲ အဲဒါကို ကျင့်သုံးပြီးတာနဲ့ မဆိုးပါဘူး ဒါပေမယ့် မင်းနဲ့ အချစ်ရေးက ကြာရှည်မခံဘူးဆိုတာ သိလာရတဲ့ ဘဝရဲ့ သဘာဝပါပဲ" },
      { start: 58, end: 71, japanese: "もっと違う設定で　もっと違う関係で 出会える世界線　選べたらよかった", romaji: "motto chigau settei de motto chigau kankei de deaeru sekai sen erabe tara yokatta", myanmar: "မတူညီတဲ့အခြေအနေနဲ့ မတူညီတဲ့ဆက်ဆံရေးတစ်ခုနဲ့ ဆုံတွေ့နိုင်မယ့် ကမ္ဘာ့စည်းကို ရွေးချယ်နိုင်ပါစေလို့ ဆုတောင်းပါတယ်။" },
      { start: 71, end: 85, japanese: "もっと違う性格で　もっと違う価値観で 愛を伝えられたらいいな　そう願っても無駄だから", romaji: "motto chigau seikaku de motto chigau kachi kan de ai o tsutae rare tara ii na sō negatte mo muda da kara", myanmar: "မတူညီတဲ့ ကိုယ်ရည်ကိုယ်သွေးနဲ့ မတူညီတဲ့ တန်ဖိုးတွေနဲ့အတူ မင်းကို ငါ့အချစ်ကို ပေးစွမ်းနိုင်ပါစေလို့ ဆုတောင်းပါတယ်။ အဲဒါကို လိုချင်တာ အသုံးမကျဘူး။" },
      { start: 85, end: 106, japanese: "グッバイ 君の運命のヒトは僕じゃない 辛いけど否めない　でも離れ難いのさ その髪に触れただけで　痛いや　いやでも 甘いな　いやいや", romaji: "gutsu bai kimi no ummei no hito wa boku ja nai tsurai kedo iname nai demo hanare gatai no sa sono kami ni fure ta dake de itai ya iya demo amai na iya iya", myanmar: "နှုတ်ဆက်ပါတယ် မင်းအတွက် ရည်မှန်းထားတဲ့သူမဟုတ်ပါဘူး နာကျင်ပေမယ့် ငြင်းလို့မရပေမယ့် ဆံပင်ကိုထိရုံနဲ့ နာကျင်နေတော့ ထားခဲ့ဖို့က ခက်တယ်မဟုတ်ပေမယ့် အရမ်းချိုတယ် မဟုတ်ဘူး မဟုတ်ဘူး၊" },
      { start: 106, end: 131, japanese: "グッバイ それじゃ僕にとって君は何？ 答えは分からない　分かりたくもないのさ たったひとつ確かなことがあるとするのならば 「君は綺麗だ」", romaji: "gutsu bai sore ja boku nitotte kimi wa nani ? kotae wa wakara nai wakari taku mo nai no sa tatta hitotsu tashika na koto ga aru to suru no nara ba kimi wa kirei da", myanmar: "နှုတ်ဆက်လိုက်ပါ ဒါဆို မင်းက ငါ့အတွက် ဘာလဲ။ အဖြေကို မသိဘူး၊ သိချင်တောင် မသိချင်တော့ဘူး။ သေချာတာတစ်ခု ရှိရင် မင်းက လှတယ်။" },
      { start: 133, end: 153, japanese: "誰かが偉そうに 語る恋愛の論理 何ひとつとしてピンとこなくて 飛行機の窓から見下ろした 知らない街の夜景みたいだ", romaji: "dare ka ga era sō ni kataru ren'ai no ronri nani hitotsu toshite pin toko naku te hikōki no mado kara mioroshi ta shira nai machi no yakei mitai da", myanmar: "တစ်စုံတစ်ယောက်အကြောင်း မောက်မာစွာပြောနေသည့် အချစ်၏ယုတ္တိယုတ္တိသည် လုံးဝအဓိပ္ပာယ်မရှိပါ၊ လေယာဉ်ပြတင်းပေါက်မှ အမည်မသိမြို့တစ်မြို့၏ ညမြင်ကွင်းကို ငုံ့ကြည့်နေရသလိုပင်။" },
      { start: 153, end: 164, japanese: "もっと違う設定で　もっと違う関係で 出会える世界線　選べたらよかった", romaji: "motto chigau settei de motto chigau kankei de deaeru sekai sen erabe tara yokatta", myanmar: "မတူညီတဲ့အခြေအနေနဲ့ မတူညီတဲ့ဆက်ဆံရေးတစ်ခုနဲ့ ဆုံတွေ့နိုင်မယ့် ကမ္ဘာ့စည်းကို ရွေးချယ်နိုင်ပါစေလို့ ဆုတောင်းပါတယ်။" },
      { start: 164, end: 180, japanese: "いたって純な心で　叶った恋を抱きしめて 「好きだ」とか無責任に言えたらいいな そう願っても虚しいのさ", romaji: "itatte jun na kokoro de kanatta koi o dakishime te suki da toka musekinin ni ie tara ii na sō negatte mo munashii no sa", myanmar: "ဖြူစင်တဲ့နှလုံးသားနဲ့ စစ်မှန်တဲ့အချစ်ကို ထွေးပွေ့ပြီး 'ချစ်တယ်' လို့ တာဝန်မဲ့စွာ ပြောချင်ပါတယ်။ ငါဆန္ဒရှိရင်တောင် အလကားပဲ။" },
      { start: 180, end: 204, japanese: "グッバイ 繋いだ手の向こうにエンドライン 引き伸ばすたびに　疼きだす未来には 君はいない　その事実に Cry... そりゃ苦しいよな", romaji: "gutsu bai tsunai da te no mukō ni endorain hikinobasu tabi ni uzuki dasu mirai ni wa kimi wa i nai sono jijitsu ni Cry ... sorya kurushii yo na", myanmar: "နှုတ်ဆက်ပါသည်၊ ကျွန်ုပ်တို့၏ချိတ်ဆက်ထားသောလက်များထက် အဆုံးလိုင်းတစ်ခုရှိပါသည်။ ဆန့်လိုက်တိုင်း နာကျင်လာသည်။ နောင်တွင် သင်သည် ဤနေရာတွင် မရှိပါ။ ငိုရတာ နာကျင်ရမှာပဲ မဟုတ်လား ။" },
      { start: 221, end: 242, japanese: "グッバイ 君の運命のヒトは僕じゃない 辛いけど否めない　でも離れ難いのさ その髪に触れただけで　痛いや いやでも　甘いな　いやいや", romaji: "gutsu bai kimi no ummei no hito wa boku ja nai tsurai kedo iname nai demo hanare gatai no sa sono kami ni fure ta dake de itai ya iya demo amai na iya iya", myanmar: "နှုတ်ဆက်ပါတယ် မင်းအတွက် ရည်မှန်းထားတဲ့သူမဟုတ်ပါဘူး နာကျင်ပေမယ့် ငြင်းလို့မရပေမယ့် ထားထားဖို့ခက်တဲ့ ဆံပင်ကိုထိလိုက်ရုံနဲ့ နာကျင်လိုက်တာမဟုတ်ပေမယ့် ချိုမြိန်တယ် မဟုတ်ဘူး" },
      { start: 242, end: 266, japanese: "グッバイ それじゃ僕にとって君は何？ 答えは分からない　分かりたくもないのさ たったひとつ確かなことがあるとするのならば 「君は綺麗だ」", romaji: "gutsu bai sore ja boku nitotte kimi wa nani ? kotae wa wakara nai wakari taku mo nai no sa tatta hitotsu tashika na koto ga aru to suru no nara ba kimi wa kirei da", myanmar: "နှုတ်ဆက်ပါတယ် ဒါဆို မင်းက ငါ့အတွက် ဘာလဲ။ အဖြေကို မသိဘူး၊ သိချင်လည်း မသိချင်ဘူး။ သေချာတာတစ်ခု ရှိရင် မင်းက လှတယ်။" },
      { start: 266, end: 276, japanese: "それもこれもロマンスの定めなら　悪くないよな", romaji: "sore mo kore mo romansu no sadame nara waruku nai yo na", myanmar: "အချစ်ရေးရဲ့ စံနှုန်းတစ်ခုဆိုရင် မဆိုးပါဘူး။" },
      { start: 276, end: 290, japanese: "永遠も約束もないけれど 「とても綺麗だ」", romaji: "eien mo yakusoku mo nai keredo totemo kirei da", myanmar: "ထာဝရ သို့မဟုတ် ကတိ မရှိဘူး၊ ဒါပေမယ့် 'ဒါက အရမ်းလှတယ်။'" },
    ],
  },
  {
    id: "6",
    title: "粉雪 / レミオロメン",
    titleMm: "Konayuki / Remioromen",
    videoId: "Tic_P-ujcQM",
    level: "中級",
    subtitles: [
      { start: 25, end: 36, japanese: "粉雪舞う季節はいつもすれ違い", romaji: "koyuki mau kisetsu wa itsumo surechigai", myanmar: "နှင်းမှုန်ထူထပ်သောရာသီတွင် ကျွန်ုပ်တို့သည် အမြဲတစေ ဖြတ်သန်းကြသည်။" },
      { start: 36, end: 47, japanese: "人混みに紛れても同じ空見てるのに", romaji: "hitogomi ni magire te mo onaji sora mi teru noni", myanmar: "လူအုပ်ကြားထဲမှာ ပျောက်သွားရင်တောင် ကောင်းကင်ကိုပဲ မော့ကြည့်နေတုန်းပဲ။" },
      { start: 47, end: 55, japanese: "風に吹かれて 似たように凍えるのに", romaji: "kaze ni fuka re te ni ta yō ni kogoeru noni", myanmar: "လေတိုက်လို့ အေးခဲနေပေမယ့်လည်း ဒီလိုပါပဲ။" },
      { start: 60, end: 72, japanese: "僕は君の全てなど知ってはいないだろう", romaji: "boku wa kimi no subete nado shitte wa i nai daro u", myanmar: "ငါမင်းအကြောင်းအကုန်မသိဘူး။" },
      { start: 72, end: 82, japanese: "それでも一億人から君を見つけたよ", romaji: "soredemo ichi oku nin kara kimi o mitsuke ta yo", myanmar: "သို့သော်လည်း လူသန်း 100 မှာ မင်းကို ငါတွေ့ခဲ့တယ်။" },
      { start: 82, end: 91, japanese: "根拠はないけど 本気で思ってるんだ", romaji: "konkyo wa nai kedo honki de omotteru n da", myanmar: "ငါ့မှာ သက်သေမရှိဘူး၊ ဒါပေမယ့် ငါတကယ်ထင်တာ။" },
      { start: 91, end: 97, japanese: "些細な言い合いもなくて", romaji: "sasai na īai mo naku te", myanmar: "အသေးအမွှား ငြင်းခုံမှုများ မရှိခဲ့ပါ။" },
      { start: 97, end: 104, japanese: "同じ時間を生きてなどいけない", romaji: "onaji jikan o iki te nado ike nai", myanmar: "ငါတို့က တစ်ချိန်တည်းမှာ နေလို့မရဘူး" },
      { start: 104, end: 110, japanese: "素直になれないなら", romaji: "sunao ni nare nai nara", myanmar: "မရိုးသားနိုင်ရင်" },
      { start: 110, end: 121, japanese: "喜びも悲しみも虚しいだけ", romaji: "yorokobi mo kanashimi mo munashii dake", myanmar: "ပျော်ရွှင်မှုနှင့် ဝမ်းနည်းမှု နှစ်ခုစလုံးသည် အချည်းနှီးဖြစ်သည်။" },
      { start: 121, end: 133, japanese: "粉雪 ねえ 心まで白く染められたなら", romaji: "koyuki nē kokoro made shiroku some rare ta nara", myanmar: "နှင်းမှုန် ၊ ဟေး မင်းရဲ့ နှလုံးသားကိုတောင် အဖြူရောင်ဆေးဆိုးထားရင် ၊" },
      { start: 133, end: 143, japanese: "二人の孤独を分け合う事が出来たのかい", romaji: "ni nin no kodoku o wakeau koto ga deki ta no kai", myanmar: "ငါတို့ရဲ့ အထီးကျန်မှုကို မင်း မျှဝေပေးနိုင်မလား။" },
      { start: 154, end: 165, japanese: "僕は君の心に耳を押し当てて", romaji: "boku wa kimi no kokoro ni mimi o oshi ate te", myanmar: "ငါ့နားကို မင်းနှလုံးသားကို ငါဖိထားတယ်။" },
      { start: 165, end: 176, japanese: "その声のする方へすっと深くまで", romaji: "sono koe no suru hō e sutto fukaku made", myanmar: "ထိုအသံ၏ ဦးတည်ရာဆီသို့ လေးလေးနက်နက်" },
      { start: 176, end: 185, japanese: "下りてゆきたい そこでもう一度会おう", romaji: "ori te yuki tai sokode mōichido aō", myanmar: "ဆင်းချင်တယ်၊ ဟိုမှာ ပြန်ဆုံကြရအောင်" },
      { start: 185, end: 191, japanese: "分かり合いたいなんて", romaji: "wakari ai tai nante", myanmar: "တစ်ယောက်နဲ့တစ်ယောက် နားလည်ပေးစေချင်တယ်။" },
      { start: 191, end: 197, japanese: "上辺を撫でていたのは僕の方", romaji: "uwabe o nade te i ta no wa boku no hō", myanmar: "ငါက ထိပ်ကို လှမ်းကိုင်တဲ့သူ။" },
      { start: 197, end: 203, japanese: "君のかじかんだ手も", romaji: "kimi no kajikan da te mo", myanmar: "မင်းရဲ့ အေးခဲနေတဲ့ လက်တွေလည်း" },
      { start: 203, end: 215, japanese: "握りしめることだけで繋がってたのに", romaji: "nigirishimeru koto dake de tsunagatte ta noni", myanmar: "တစ်ယောက်ကိုတစ်ယောက် ဆုပ်ကိုင်ထားရုံနဲ့ အဆက်အသွယ်ရှိပေမယ့်" },
      { start: 215, end: 227, japanese: "粉雪 ねえ 永遠を前にあまりに脆く", romaji: "koyuki nē eien o mae ni amarini moroku", myanmar: "နှင်းမှုန်၊ ဟေး၊ မင်းဟာ ထာဝရရှေ့မှာ အရမ်းနုနယ်တယ်။" },
      { start: 227, end: 236, japanese: "ざらつくアスファルトの上シミになってゆくよ", romaji: "zaratsuku asufaruto no ue shimi ni natte yuku yo", myanmar: "ကြမ်းတမ်းသော ကတ္တရာပေါ်တွင် စွန်းထင်းလာသည်။" },
      { start: 259, end: 271, japanese: "粉雪 ねえ 時に頼りなく心は揺れる", romaji: "koyuki nē tokini tayori naku kokoro wa yureru", myanmar: "နှင်းမှုန်တွေ ဟေး တခါတရံမှာ ငါ့နှလုံးသားက မယုံနိုင်လောက်အောင် ခုန်နေတယ်။" },
      { start: 271, end: 282, japanese: "それでも僕は君のこと守り続けたい", romaji: "soredemo boku wa kimi no koto mamori tsuzuke tai", myanmar: "ဒါတောင် ငါ မင်းကို ဆက်ပြီး ကာကွယ်ချင်သေးတယ်။" },
      { start: 282, end: 294, japanese: "粉雪 ねえ 心まで白く染められたなら", romaji: "koyuki nē kokoro made shiroku some rare ta nara", myanmar: "နှင်းမှုန် ၊ ဟေး မင်းရဲ့ နှလုံးသားကိုတောင် အဖြူရောင်ဆေးဆိုးထားရင် ၊" },
      { start: 294, end: 307, japanese: "二人の孤独を包んで空にかえすから", romaji: "ni nin no kodoku o tsutsun de sora ni kaesu kara", myanmar: "ငါတို့ရဲ့ အထီးကျန်မှုကို ဖုံးကွယ်ပြီး ကောင်းကင်ကို ပြန်ပေးမယ်။" },
    ],
  },
  {
    id: "7",
    title: "Lemon / 米津玄師",
    titleMm: "Lemon / 米津玄師",
    videoId: "SX_ViT4Ra7k",
    level: "上級",
    subtitles: [
      { start: 2, end: 8, japanese: "夢ならばどれほどよかったでしょう", romaji: "yume nara ba dorehodo yokatta desho u", myanmar: "အိပ်မက်ဆိုရင် ဘယ်လောက်ကောင်းမလဲ" },
      { start: 8, end: 13, japanese: "未だにあなたのことを夢にみる", romaji: "imadani anata no koto o yume ni miru", myanmar: "ယခုတိုင် သင့်ကို အိပ်မက်မြင်နေဆဲ" },
      { start: 13, end: 19, japanese: "忘れた物を取りに帰るように", romaji: "wasure ta mono o tori ni kaeru yō ni", myanmar: "မေ့သွားသောအရာကို ပြန်ယူဖို့ ပြန်သွားသလို" },
      { start: 19, end: 27, japanese: "古びた思い出の埃を払う", romaji: "furubi ta omoide no hokori o harau", myanmar: "နောက်ကျသောမှတ်ဥာဏ်၏ ဖုန်ကို ဖယ်ရှား" },
      { start: 27, end: 33, japanese: "戻らない幸せがあることを", romaji: "modora nai shiawase ga aru koto o", myanmar: "ပြန်မလာနိုင်သော ပျော်ရွှင်မှုရှိကြောင်း" },
      { start: 33, end: 38, japanese: "最後にあなたが教えてくれた", romaji: "saigo ni anata ga oshie te kure ta", myanmar: "နောက်ဆုံးတွင် သင်သင်ပေးသွားခဲ့" },
      { start: 38, end: 44, japanese: "言えずに隠してた昏い過去も", romaji: "ie zu ni kakushi te ta 昏 i kako mo", myanmar: "ပြောမရ ဝှက်ထားသော မှောင်မိုက်သောအတိတ်ကိုလည်း" },
      { start: 44, end: 49, japanese: "あなたがいなきゃ永遠に昏いまま", romaji: "anata ga i nakya eien ni 昏 ima ma", myanmar: "သင်မရှိဘဲ ထာဝရ မှောင်မိုက်နေမည်" },
      { start: 49, end: 55, japanese: "きっともうこれ以上 傷つくことなど", romaji: "kitto mō kore ijō kizutsuku koto nado", myanmar: "ဒီထက်ပို၍ နာကျင်ဖွယ်မရှိ" },
      { start: 55, end: 60, japanese: "ありはしないとわかっている", romaji: "ari wa shi nai to wakatte iru", myanmar: "မဖြစ်နိုင်ကြောင်း သိနေ" },
      { start: 60, end: 63, japanese: "あの日の悲しみさえ", romaji: "ano hi no kanashimi sae", myanmar: "ထိုနေ့၏ ဝမ်းနည်းမှုပင်" },
      { start: 63, end: 65, japanese: "あの日の苦しみさえ", romaji: "ano hi no kurushimi sae", myanmar: "ထိုနေ့၏ နာကျင်မှုပင်" },
      { start: 65, end: 71, japanese: "そのすべてを愛してた あなたとともに", romaji: "sono subete o aishi te ta anata totomoni", myanmar: "ထိုအရာအားလုံးကို သင်နှင့်အတူ ချစ်ခဲ့" },
      { start: 71, end: 74, japanese: "胸に残り離れない", romaji: "mune ni nokori hanare nai", myanmar: "ရင်ထဲ ကျန်ရစ် မဆိတ်မသုဉ်း" },
      { start: 74, end: 77, japanese: "苦いレモンの匂い", romaji: "nigai remon no nioi", myanmar: "ခါးသောသံပရာ၏ နံ့သာ" },
      { start: 77, end: 82, japanese: "雨が降り止むまでは帰れない", romaji: "ame ga ori yamu made wa kaere nai", myanmar: "မိုးရပ်သည်အထိ ပြန်မသွားနိုင်" },
      { start: 82, end: 99, japanese: "今でもあなたはわたしの光", romaji: "ima demo anata wa watashi no hikari", myanmar: "ယနေ့တိုင် သင်သည် ကျွန်မ၏ အလင်းရောင်" },
      { start: 99, end: 104, japanese: "暗闇であなたの背をなぞった", romaji: "kurayami de anata no se o nazotta", myanmar: "မှောင်ထဲတွင် သင်၏ ကျောကို ကိုင်တွယ်ခဲ့" },
      { start: 104, end: 110, japanese: "その輪郭を鮮明に覚えている", romaji: "sono rinkaku o semmei ni oboe te iru", myanmar: "ထိုပုံသဏ္ဌာန်ကို ရှင်းရှင်းလင်းလင်း မှတ်မိနေ" },
      { start: 110, end: 116, japanese: "受け止めきれないものと出会うたび", romaji: "uketome kire nai mono to deau tabi", myanmar: "မနိုင်မနင်းတာနှင့် တွေ့ဆုံတိုင်း" },
      { start: 116, end: 121, japanese: "溢れてやまないのは涙だけ", romaji: "afure te yama nai no wa namida dake", myanmar: "ရပ်မသွားနိုင်သော မျက်ရည်သာ စီးကျ" },
      { start: 121, end: 124, japanese: "何をしていたの", romaji: "nani o shi te i ta no", myanmar: "ဘာလုပ်နေတာလဲ" },
      { start: 124, end: 127, japanese: "何を見ていたの", romaji: "nani o mi te i ta no", myanmar: "ဘာကြည့်နေတာလဲ" },
      { start: 127, end: 132, japanese: "わたしの知らない横顔で", romaji: "watashi no shira nai yokogao de", myanmar: "ကျွန်မမသိသော နံဘေးမှ မျက်နှာဖြင့်" },
      { start: 132, end: 135, japanese: "どこかであなたが今", romaji: "doko ka de anata ga ima", myanmar: "တစ်နေရာတွင် သင်ယခု" },
      { start: 135, end: 137, japanese: "わたしと同じ様な", romaji: "watashi to onaji yō na", myanmar: "ကျွန်မကဲ့သို့" },
      { start: 137, end: 143, japanese: "涙にくれ 淋しさの中にいるなら", romaji: "namida ni kure sabishi sa no naka ni iru nara", myanmar: "မျက်ရည်ကျ တောင့်တနာမှုထဲ ရှိနေမည်ဆိုလျှင်" },
      { start: 143, end: 149, japanese: "わたしのことなどどうか 忘れてください", romaji: "watashi no koto nado dōka wasure te kudasai", myanmar: "ကျွန်မကို ကျေးဇူးပြု၍ မေ့ပေးပါ" },
      { start: 149, end: 154, japanese: "そんなことを心から願うほどに", romaji: "sonna koto o kokorokara negau hodo ni", myanmar: "ထိုသို့ ရင်ထဲမှ ဆုတောင်းသည်အထိ" },
      { start: 154, end: 163, japanese: "今でもあなたはわたしの光", romaji: "ima demo anata wa watashi no hikari", myanmar: "ယနေ့တိုင် သင်သည် ကျွန်မ၏ အလင်းရောင်" },
      { start: 163, end: 174, japanese: "自分が思うより 恋をしていたあなたに", romaji: "jibun ga omou yori koi o shi te i ta anata ni", myanmar: "မိမိထင်ထားသည်ထက် သင့်ကို ချစ်ခဲ့" },
      { start: 174, end: 185, japanese: "あれから思うように 息ができない", romaji: "are kara omou yō ni iki ga deki nai", myanmar: "ထိုအချိန်မှစ၍ ကောင်းကောင်း နှာမပူ" },
      { start: 185, end: 195, japanese: "あんなに側にいたのにまるで嘘みたい", romaji: "annani gawa ni i ta noni marude uso mitai", myanmar: "ဒီလောက်နားတွင်ရှိနေသည်မှာ မဟုတ်မမှန်ဟု ထင်ရ" },
      { start: 195, end: 212, japanese: "とても忘れられないそれだけが確か", romaji: "totemo wasure rare nai sore dake ga tashika", myanmar: "မမေ့နိုင်ပါ ထိုအရာသာ သေချာ" },
      { start: 212, end: 214, japanese: "あの日の悲しみさえ", romaji: "ano hi no kanashimi sae", myanmar: "ထိုနေ့၏ ဝမ်းနည်းမှုပင်" },
      { start: 214, end: 217, japanese: "あの日の苦しみさえ", romaji: "ano hi no kurushimi sae", myanmar: "ထိုနေ့၏ နာကျင်မှုပင်" },
      { start: 217, end: 222, japanese: "その全てを愛してたあなたと共に", romaji: "sono subete o aishi te ta anata totomoni", myanmar: "ထိုအားလုံးကို သင်နှင့်အတူ ချစ်ခဲ့" },
      { start: 222, end: 225, japanese: "胸に残り離れない", romaji: "mune ni nokori hanare nai", myanmar: "ရင်ထဲ ကျန်ရစ် မဆိတ်မသုဉ်း" },
      { start: 225, end: 229, japanese: "苦いレモンの匂い", romaji: "nigai remon no nioi", myanmar: "ခါးသောသံပရာ၏ နံ့သာ" },
      { start: 229, end: 234, japanese: "雨が降り止むまでは帰れない", romaji: "ame ga ori yamu made wa kaere nai", myanmar: "မိုးရပ်သည်အထိ ပြန်မသွားနိုင်" },
      { start: 234, end: 240, japanese: "切り分けた果実の片方の様に", romaji: "kiriwake ta kajitsu no katahō no yō ni", myanmar: "ခွဲထားသောသစ်သီး၏ တစ်ဖက်ကဲ့သို့" },
      { start: 240, end: 245, japanese: "今でもあなたはわたしの光", romaji: "ima demo anata wa watashi no hikari", myanmar: "ယနေ့တိုင် သင်သည် ကျွန်မ၏ အလင်းရောင်" },
    ],
  },
  {
    id: "8",
    title: "マリーゴールド / あいみょん",
    titleMm: "マリーゴールド / あいみょん",
    videoId: "0xSiBpUdW4E",
    level: "中級",
    subtitles: [
      { start: 21, end: 24.5, japanese: "風の強さがちょっと", romaji: "kaze no tsuyo sa ga chotto", myanmar: "လေ၏ပြင်းအားသည် နည်းနည်း" },
      { start: 24.6, end: 30, japanese: "心を揺さぶりすぎて", romaji: "kokoro o yusaburi sugi te", myanmar: "ရင်ကို လွန်ကဲစွာ ထိတုန်ခိုက်၍" },
      { start: 29.7, end: 39, japanese: "真面目に見つめた 君が恋しい", romaji: "majime ni mitsume ta kimi ga koishii", myanmar: "တည်တည်ကြည်ကြည် ကြည့်သောသင် ဆွတ်ဆွတ်" },
      { start: 38.9, end: 43, japanese: "でんぐり返しの日々", romaji: "dengurigaeshi no hibi", myanmar: "လဲပြောင်းလိုက်နေသော နေ့ရက်များ" },
      { start: 43.1, end: 48, japanese: "可哀想なふりをして", romaji: "kawaisō na furi o shi te", myanmar: "သနားဖွယ်ဆိုသည့် ဟန်ဆောင်၍" },
      { start: 48, end: 52.5, japanese: "だらけてみたけど", romaji: "darake te mi ta kedo", myanmar: "ပေါ့ပေါ့ပါးပါး နေကြည့်ပမ်းသော်လည်း" },
      { start: 52.6, end: 57.5, japanese: "希望の光は", romaji: "kibō no hikari wa", myanmar: "မျှော်လင့်ချက်၏ အလင်းသည်" },
      { start: 56.9, end: 62, japanese: "目の前でずっと輝いている 幸せだ", romaji: "me no mae de zutto kagayai te iru shiawase da", myanmar: "မျက်မှောက်တွင် ထာဝရ တောက်ပနေ၏ ချမ်းသာ" },
      { start: 65.2, end: 67, japanese: "麦わらの帽子の君が", romaji: "mugiwara no bōshi no kimi ga", myanmar: "မြက်ဖျားဦးထုပ်ဆောင်းသော သင်သည်" },
      { start: 70.1, end: 75, japanese: "揺れたマリーゴールドに似てる", romaji: "yure ta marī gōrudo ni ni teru", myanmar: "တုန်ခါနေသောမာရီဂိုလ်ဒ်နှင့် တူ" },
      { start: 75.1, end: 81, japanese: "あれは 空がまだ青い夏のこと", romaji: "are wa sora ga mada aoi natsu no koto", myanmar: "ထိုအချိန်က မိုးကောင်းကင် ခပ်နက်နက် နွေရာသီ" },
      { start: 79.6, end: 85, japanese: "懐かしいと笑えたあの日の恋", romaji: "natsukashii to warae ta ano hi no koi", myanmar: "ကျော်သွားသောချစ်မှုကို သတိရ၍ ရယ်မိ" },
      { start: 85, end: 89, japanese: "「もう離れないで」と", romaji: "mō hanare nai de to", myanmar: "ကျွန်မမချန်မနေပါနှင့် ဟု" },
      { start: 89, end: 93, japanese: "泣きそうな目で見つめる君を", romaji: "naki sō na me de mitsumeru kimi o", myanmar: "မျက်ရည်ကျမတတ်မျက်လုံးဖြင့် ကြည့်သောသင်ကို" },
      { start: 93, end: 97, japanese: "雲のような優しさでそっとぎゅっと", romaji: "kumo no yō na yasashi sa de sotto gyutto", myanmar: "တိမ်ကဲ့သို့ နူးညံ့ သောစွာ ဖက်ကိုင်" },
      { start: 97, end: 107, japanese: "抱きしめて 抱きしめて 離さない", romaji: "dakishime te dakishime te hanasa nai", myanmar: "ဖက်ကိုင်ဖက်ကိုင် မလွှတ်" },
      { start: 107, end: 111, japanese: "本当の気持ち全部", romaji: "hontō no kimochi zembu", myanmar: "အမှန်တကယ်ခံစားချက်အားလုံး ထုတ်ဖော်ရဲသောအားမရှိ" },
      { start: 111, end: 115, japanese: "吐き出せるほど強くはない", romaji: "hakidaseru hodo tsuyoku wa nai", myanmar: "ရောက်မည်မဟုတ်သော ပြင်းထန်မှု" },
      { start: 115, end: 120, japanese: "でも不思議なくらいに", romaji: "demo fushigi na kurai ni", myanmar: "ဒါပေမဲ့ ထူးဆန်းစွာ" },
      { start: 120, end: 124, japanese: "絶望は見えない", romaji: "zetsubō wa mie nai", myanmar: "မျှော်လင့်ချက်ကုန်ဆုံးမှုမြင်မရ" },
      { start: 124, end: 128.5, japanese: "目の奥にずっと写るシルエット", romaji: "me no oku ni zutto utsuru shiruetto", myanmar: "မျက်လုံးအတွင်း ထာဝရ ကျန်နေသောရုပ်ပုံ" },
      { start: 128.5, end: 130.5, japanese: "大好きさ", romaji: "daisuki sa", myanmar: "ပြင်းအားကျ ချစ်မိ" },
      { start: 130.5, end: 138, japanese: "柔らかな肌を寄せあい", romaji: "yawaraka na hada o yose ai", myanmar: "နူးညံ့သောအသားကို ချိတ်ဆက်" },
      { start: 138, end: 142.5, japanese: "少し冷たい空気を2人", romaji: "sukoshi tsumetai kūki o 2 nin", myanmar: "နည်းနည်းအေးသောလေကို နှစ်ယောက်တည်း" },
      { start: 142.5, end: 147, japanese: "かみしめて歩く 今日という日に 何と", romaji: "kamishime te aruku kyō toyuu hi ni nanto", myanmar: "ကြိတ်မှိတ်ကာ ဒီနေ့ ဟုဘာနာမည်မှည့်ကြမလဲ" },
      { start: 147, end: 153, japanese: "名前をつけようかなんて話して", romaji: "namae o tsukeyō ka nante hanashi te", myanmar: "ဟုစကားပြောနေ၏ ၊ အင်း" },
      { start: 153, end: 157.5, japanese: "ああ アイラブユーの言葉じゃ", romaji: "ā airabuyū no kotoba ja", myanmar: "I love you ဟုသောစကားမလုံလောက်" },
      { start: 157.5, end: 161, japanese: "足りないからとキスして", romaji: "tari nai kara to kisu shi te", myanmar: "မလုံလောက်၍ နမ်းလိုက်" },
      { start: 161, end: 166, japanese: "雲がまだ2人の影を残すから", romaji: "kumo ga mada 2 nin no kage o nokosu kara", myanmar: "တိမ်သည် နှစ်ယောက်၏အရိပ်ကျန်နေဆဲ" },
      { start: 166, end: 172, japanese: "いつまでも いつまでも このまま", romaji: "itsu made mo itsu made mo kono mama", myanmar: "ထာဝရ ထာဝရ ဤအတိုင်းနေပါ" },
      { start: 172, end: 177.5, japanese: "遥か遠い場所にいても", romaji: "haruka tōi basho ni i te mo", myanmar: "ဝေးသောနေရာတွင်ပင် ချိတ်ဆက်နေချင်" },
      { start: 177.5, end: 181.5, japanese: "繋がっていたいなあ", romaji: "tsunagatte i tai nā", myanmar: "နှစ်ယောက်၏ဆန္ဒ တူညီပါစေ" },
      { start: 181.5, end: 203, japanese: "2人の想いが 同じでありますように", romaji: "2 nin no omoi ga onaji de ari masu yō ni", myanmar: "မြက်ဖျားဦးထုပ်ဆောင်းသော သင်သည်" },
      { start: 203, end: 210, japanese: "麦わらの帽子の君が", romaji: "mugiwara no bōshi no kimi ga", myanmar: "တုန်ခါနေသောမာရီဂိုလ်ဒ်နှင့် တူ" },
      { start: 210, end: 214, japanese: "揺れたマリーゴールドに似てる", romaji: "yure ta marī gōrudo ni ni teru", myanmar: "ထိုအချိန်က မိုးကောင်းကင် ခပ်နက်နက် နွေရာသီ" },
      { start: 214, end: 217, japanese: "あれは空がまだ青い夏のこと", romaji: "are wa sora ga mada aoi natsu no koto", myanmar: "ကျော်သွားသောချစ်မှုကို သတိရ၍ ရယ်မိ" },
      { start: 217, end: 225, japanese: "懐かしいと笑えたあの日の恋", romaji: "natsukashii to warae ta ano hi no koi", myanmar: "ကျွန်မမချန်မနေပါနှင့် ဟု" },
      { start: 225, end: 228, japanese: "「もう離れないで」と", romaji: "mō hanare nai de to", myanmar: "မျက်ရည်ကျမတတ်မျက်လုံးဖြင့် ကြည့်သောသင်ကို" },
      { start: 228, end: 232, japanese: "泣きそうな目で見つめる君を", romaji: "naki sō na me de mitsumeru kimi o", myanmar: "တိမ်ကဲ့သို့ နူးညံ့ သောစွာ ဖက်ကိုင်" },
      { start: 232, end: 237.5, japanese: "雲のような優しさで そっとぎゅっと", romaji: "kumo no yō na yasashi sa de sotto gyutto", myanmar: "ဖက်ကိုင် မလွှတ်" },
      { start: 237.5, end: 240, japanese: "抱きしめて 離さない", romaji: "dakishime te hanasa nai", myanmar: "I love you ဟုသောစကားမလုံလောက်" },
      { start: 240, end: 247, japanese: "ああ アイラブユーの言葉じゃ", romaji: "ā airabuyū no kotoba ja", myanmar: "မလုံလောက်၍ နမ်းလိုက်" },
      { start: 247, end: 250.5, japanese: "足りないからとキスして", romaji: "tari nai kara to kisu shi te", myanmar: "တိမ်သည် နှစ်ယောက်၏အရိပ်ကျန်နေဆဲ" },
      { start: 250.5, end: 254, japanese: "雲がまだ2人の影を残すから", romaji: "kumo ga mada 2 nin no kage o nokosu kara", myanmar: "ထာဝရ ထာဝရ ဤအတိုင်းနေပါ" },
      { start: 254, end: 262, japanese: "いつまでも いつまでも このまま", romaji: "itsu made mo itsu made mo kono mama", myanmar: "မလွှတ်" },
      { start: 262, end: 269, japanese: "離さない", romaji: "hanasa nai", myanmar: "အင်း ထာဝရ ထာဝရ မလွှတ်" },
      { start: 269, end: 274, japanese: "ああ いつまでも いつまでも 離さない", romaji: "ā itsu made mo itsu made mo hanasa nai", myanmar: "အင်း ထာဝရ ထာဝရ မလွှတ်" },
    ],
  },
];
