export interface SubtitleCue {
  start: number;
  end: number;
  japanese: string;
  romaji: string;
  myanmar: string;
}

export interface Lesson {
  id: string;
  title: string;
  titleMm: string;
  videoId: string;
  level: string;
  subtitles: SubtitleCue[];
}

export const lessons: Lesson[] = [
  {
    id: "1",
    title: "あとひとつ / FUNKY MONKEY BABYS",
    titleMm: "Ato Hitotsu / FUNKY MONKEY BABYS",
    videoId: "bGBy80LdkPI",
    level: "N3",
    subtitles: [
      { start: 13, end: 19, japanese: "あと一粒の涙で ひと言の勇気で", romaji: "ato ichi tsubu no namida de hitokoto no yūki de", myanmar: "မျက်ရည်တစ်စက်ထပ်နဲ့ စကားတစ်ခွန်းရဲ့ ရဲစွမ်းသတ္တိနဲ့" },
      { start: 19, end: 25, japanese: "願いがかなう その時が来るって", romaji: "negai ga kanau sono toki ga kuru tte", myanmar: "ဆုတောင်းချက် ပြည့်မြောက်မည့် အချိန် ရောက်လာမယ်လို့" },
      { start: 25, end: 31, japanese: "僕は信じているから 君もあきらめないでいて", romaji: "boku wa shinji te iru kara kimi mo akirame nai de i te", myanmar: "ငါ ယုံကြည်နေတာမို့ မင်းလည်း လက်မလျှော့နဲ့" },
      { start: 31, end: 50, japanese: "何度でも この両手を あの空へ", romaji: "nan do demo kono ryōte o ano sora e", myanmar: "ဘယ်နှစ်ကြိမ်မဆို ဒီလက်နှစ်ဖက်ကို ထိုမိုးကောင်းကင်ဆီ" },
      { start: 50, end: 53, japanese: "あの日もこんな夏だった", romaji: "ano hi mo konna natsu datsu ta", myanmar: "ထိုနေ့ကလည်း ဒီလို နွေရာသီပဲ" },
      { start: 53, end: 56, japanese: "砂まじりの風が吹いていた", romaji: "suna majiri no kaze ga fui te i ta", myanmar: "သဲပါသောလေ တိုက်ခဲ့တယ်" },
      { start: 56, end: 62, japanese: "グラウンドの真上の空 夕日がまぶしくて", romaji: "guraundo no ma uwanosora yūhi ga mabushiku te", myanmar: "ကွင်းပြင်အပေါ် မိုးကောင်းကင် နေဝင်ချိန် အလွန်တောက်ပတယ်" },
      { start: 62, end: 65, japanese: "どこまで頑張ればいいんだ", romaji: "doko made gambare ba ii n da", myanmar: "ဘယ်လောက်ထိ ကြိုးစားရမှာလဲ" },
      { start: 65, end: 68, japanese: "ぎゅっと唇を噛みしめた", romaji: "gyutto kuchibiru o kamishime ta", myanmar: "နှုတ်ခမ်းကို တင်းကြပ်စွာ ကိုက်မိတယ်" },
      { start: 68, end: 74, japanese: "そんな時 同じ目をした 君に出会ったんだ", romaji: "sonna toki onaji me o shi ta kimi ni deatta n da", myanmar: "ထိုအချိန် တူညီသောမျက်လုံးရှိသော မင်းနဲ့ တွေ့ဆုံခဲ့တယ်" },
      { start: 74, end: 86, japanese: "そう 簡単じゃないからこそ 夢はこんなに輝くんだと", romaji: "sō kantan ja nai kara koso yume wa konnani kagayaku n da to", myanmar: "ဟုတ်တယ် လွယ်မဟုတ်တာကြောင့်ပဲ အိပ်မက်က ဒီလောက် တောက်ပနေတယ်" },
      { start: 86, end: 98, japanese: "そう あの日の君の言葉 今でも胸に抱きしめてるよ", romaji: "sō ano hi no kimi no kotoba ima demo mune ni dakishime teru yo", myanmar: "ဟုတ်တယ် ထိုနေ့ မင်းရဲ့ စကားကို အခုထိ ရင်ခွင်မှာ ဆုပ်ကိုင်ထားတယ်" },
      { start: 98, end: 104, japanese: "あと一粒の涙で ひと言の勇気で", romaji: "ato ichi tsubu no namida de hitokoto no yūki de", myanmar: "မျက်ရည်တစ်စက်ထပ်နဲ့ စကားတစ်ခွန်းရဲ့ ရဲစွမ်းသတ္တိနဲ့" },
      { start: 104, end: 110, japanese: "願いがかなう その時が来るって", romaji: "negai ga kanau sono toki ga kuru tte", myanmar: "ဆုတောင်းချက် ပြည့်မြောက်မည့် အချိန် ရောက်လာမယ်လို့" },
      { start: 110, end: 116, japanese: "僕は信じてるから 君もあきらめないでいて", romaji: "boku wa shinji teru kara kimi mo akirame nai de i te", myanmar: "ငါ ယုံကြည်နေတာမို့ မင်းလည်း လက်မလျှော့နဲ့" },
      { start: 116, end: 121, japanese: "何度でも この両手を", romaji: "nan do demo kono ryōte o", myanmar: "ဘယ်နှစ်ကြိမ်မဆို ဒီလက်နှစ်ဖက်ကို" },
      { start: 121, end: 134, japanese: "あの空へ のばして あの空へ", romaji: "ano sora e nobashi te ano sora e", myanmar: "ထိုမိုးကောင်းကင်ဆီ ဆန့်ကာ ထိုမိုးကောင်းကင်ဆီ" },
      { start: 134, end: 138, japanese: "いつもどうしても素直になれずに", romaji: "itsumo dōshitemo sunao ni nare zu ni", myanmar: "အမြဲ ဘာကြောင့်မှန်းမသိ ရိုးသားစွာမနေနိုင်ဘဲ" },
      { start: 138, end: 141, japanese: "自信なんてまるで持てずに", romaji: "jishin nante marude mote zu ni", myanmar: "ယုံကြည်မှုလည်း လုံးဝမရှိဘဲ" },
      { start: 141, end: 147, japanese: "校舎の裏側 人目を気にして歩いていた", romaji: "kōsha no uragawa hitome o ki ni shi te arui te i ta", myanmar: "ကျောင်းနောက်ဖေး သူများမျက်စိကို သတိထားကာ လျှောက်ခဲ့တယ်" },
      { start: 147, end: 150, japanese: "誰かとぶつかりあうことを", romaji: "dare ka to butsukari au koto o", myanmar: "တစ်ယောက်ယောက်နဲ့ ရင်ဆိုင်တာကို" },
      { start: 150, end: 153, japanese: "心のどこかで遠ざけた", romaji: "kokoro no doko ka de tōzake ta", myanmar: "နှလုံးသားထဲ တစ်နေရာမှာ ဝေးကွာအောင် ထားခဲ့တယ်" },
      { start: 153, end: 156, japanese: "それは本当の自分を", romaji: "sore wa hontō no jibun o", myanmar: "ဒါက တကယ်ကိုယ့်ကိုယ်ကို" },
      { start: 156, end: 160, japanese: "見せるのが怖いだけだったんだと", romaji: "miseru no ga kowai dake datsu ta n da to", myanmar: "ပြဖို့ ကြောက်ရွံ့ရုံသာ ဖြစ်ကြောင်း" },
      { start: 160, end: 164, japanese: "教えてくれたのは", romaji: "oshie te kure ta no wa", myanmar: "သွန်သင်ပေးခဲ့တာ" },
      { start: 164, end: 171, japanese: "君と過ごした今日までの日々", romaji: "kimi to sugoshi ta kyō made no hibi", myanmar: "မင်းနဲ့ ဖြတ်သန်းခဲ့သောနေ့ရက်တွေ ဖြစ်တယ်" },
      { start: 171, end: 176, japanese: "そう初めて口に出来た", romaji: "sō hajimete kuchi ni deki ta", myanmar: "ဟုတ်တယ် ပထမဆုံး ပြောနိုင်ခဲ့တယ်" },
      { start: 176, end: 183, japanese: "泣きたいくらいの本当の夢を", romaji: "naki tai kurai no hontō no yume o", myanmar: "ငိုချင်လောက်သော တကယ့်အိပ်မက်ကို" },
      { start: 183, end: 189, japanese: "あとひとつの坂道を ひとつだけの夜を", romaji: "ato hitotsu no sakamichi o hitotsu dake no yoru o", myanmar: "နောက်တစ်ခု တောင်ကြားလမ်း တစ်ညတည်းသော ညကို" },
      { start: 189, end: 195, japanese: "越えられたなら 笑える日がくるって", romaji: "koe rare ta nara waraeru hi ga kurutte", myanmar: "ကျော်လွန်နိုင်ရင် ရယ်မောနိုင်သောနေ့ ရောက်လာမယ်လို့" },
      { start: 195, end: 202, japanese: "今日も信じてるから 君もあきらめないでいて", romaji: "kyō mo shinji teru kara kimi mo akirame nai de i te", myanmar: "ဒီနေ့လည်း ယုံကြည်နေတာမို့ မင်းလည်း လက်မလျှော့နဲ့" },
      { start: 202, end: 206, japanese: "何度でも この両手を", romaji: "nan do demo kono ryōte o", myanmar: "ဘယ်နှစ်ကြိမ်မဆို ဒီလက်နှစ်ဖက်ကို" },
      { start: 206, end: 219, japanese: "あの空へ", romaji: "ano sora e", myanmar: "ထိုမိုးကောင်းကင်ဆီ" },
      { start: 219, end: 224, japanese: "あつくなっても無駄なんて言葉", romaji: "atsuku natte mo muda nante kotoba", myanmar: "စိတ်အားထက်သန်ရင် အချည်းနှီးဆိုတဲ့ စကား" },
      { start: 224, end: 231, japanese: "聞き飽きたよ もしもそうだとしても", romaji: "kiki aki ta yo moshimo sō da toshite mo", myanmar: "ကြားငြီးပြီ အဲဒီလို ဖြစ်ပါစေ" },
      { start: 231, end: 239, japanese: "抑えきれないこの気持ちを 希望と呼ぶなら", romaji: "osae kire nai kono kimochi o kibō to yobu nara", myanmar: "ထိန်းမနိုင်တဲ့ ဒီစိတ်ကို မျှော်လင့်ချက်လို့ ခေါ်မယ်ဆိုရင်" },
      { start: 239, end: 250, japanese: "いったい 誰が止められると言うのだろう", romaji: "ittai dare ga tome rareru to iu no daro u", myanmar: "တကယ်တော့ ဘယ်သူက တားဆီးနိုင်မယ်လို့ ဆိုကြသလဲ" },
      { start: 250, end: 256, japanese: "あと一粒の涙が あとひと言の勇気が", romaji: "ato ichi tsubu no namida ga ato hitokoto no yūki ga", myanmar: "မျက်ရည်တစ်စက် ရဲစွမ်းသတ္တိ နောက်တစ်ခွန်း" },
      { start: 256, end: 262, japanese: "明日を変えるその時を見たんだ", romaji: "ashita o kaeru sono toki o mi ta n da", myanmar: "မနက်ဖြန်ကို ပြောင်းမည့် အချိန်ကို မြင်ခဲ့တယ်" },
      { start: 262, end: 268, japanese: "なくしかけた光 君が思い出させてくれた", romaji: "nakushi kake ta hikari kimi ga omoidasa se te kure ta", myanmar: "ဆုံးရှုံးတော့မည့် အလင်းကို မင်းက သတိရစေခဲ့တယ်" },
      { start: 268, end: 274, japanese: "あの日の景色 忘れない", romaji: "ano hi no keshiki wasure nai", myanmar: "ထိုနေ့ မြင်ကွင်းကို မမေ့နိုင်ဘူး" },
      { start: 274, end: 281, japanese: "あと一粒の涙で ひと言の勇気で", romaji: "ato ichi tsubu no namida de hitokoto no yūki de", myanmar: "မျက်ရည်တစ်စက်ထပ်နဲ့ ရဲစွမ်းသတ္တိတစ်ခွန်းနဲ့" },
      { start: 281, end: 286, japanese: "願いがかなう その時が来るって", romaji: "negai ga kanau sono toki ga kuru tte", myanmar: "ဆုတောင်းချက် ပြည့်မြောက်မည့် အချိန် ရောက်လာမယ်လို့" },
      { start: 286, end: 293, japanese: "僕は信じてるから 君もあきらめないでいて", romaji: "boku wa shinji teru kara kimi mo akirame nai de i te", myanmar: "ငါ ယုံကြည်နေတာမို့ မင်းလည်း လက်မလျှော့နဲ့" },
      { start: 293, end: 298, japanese: "何度でも この両手を", romaji: "nan do demo kono ryōte o", myanmar: "ဘယ်နှစ်ကြိမ်မဆို ဒီလက်နှစ်ဖက်ကို" },
      { start: 298, end: 999, japanese: "あの空へ のばして あの空へ", romaji: "ano sora e nobashi te ano sora e", myanmar: "ထိုမိုးကောင်းကင်ဆီ ဆန့်ကာ ထိုမိုးကောင်းကင်ဆီ" },
    ],
  },
  {
    id: "2",
    title: "secret base〜君がくれたもの〜 / ZONE",
    titleMm: "secret base / ZONE",
    videoId: "ACo60qnd_Lc",
    level: "N3",
    subtitles: [
      { start: 14, end: 18, japanese: "君と夏の終わり 将来の夢", romaji: "kimi to natsu no owari shōrai no yume", myanmar: "မင်းနဲ့ နွေရာသီကုန်ချိန် အနာဂတ်အိပ်မက်" },
      { start: 18, end: 22, japanese: "大きな希望 忘れない", romaji: "ōkina kibō wasure nai", myanmar: "မြော်လင့်ချက်ကြီး မမေ့နိုင်ဘူး" },
      { start: 22, end: 24, japanese: "10年後の8月", romaji: "10 nen go no 8 tsuki", myanmar: "၁၀ နှစ်နောက် သြဂုတ်လမှာ" },
      { start: 24, end: 29, japanese: "また出会えるの 信じて", romaji: "mata deaeru no shinji te", myanmar: "တစ်ဖန်တွေ့နိုင်မယ်လို့ ယုံကြည်တယ်" },
      { start: 54, end: 61, japanese: "出会いはふっとした瞬間 帰り道の交差点で", romaji: "deai wa futto shi ta shunkan kaerimichi no kōsaten de", myanmar: "တွေ့ဆုံမှုက မမျှော်ထားသောအချိန် အပြန်လမ်း လမ်းဆုံမှာ" },
      { start: 61, end: 68, japanese: "声をかけてくれたね 「一緒に帰ろう」", romaji: "koe o kake te kure ta ne issho ni kaerō", myanmar: "ခေါ်ဆိုပေးခဲ့တယ် 'အတူတူ ပြန်ကြရအောင်'" },
      { start: 68, end: 76, japanese: "僕は照れくさそうに カバンで顔を隠しながら", romaji: "boku wa terekusa sō ni kaban de kao o kakushi nagara", myanmar: "ကျွန်တော် ရှက်ရွံ့ဟန်နဲ့ အိတ်နဲ့မျက်နှာဖုံးရင်း" },
      { start: 76, end: 83, japanese: "本当はとてもとても 嬉しかったよ", romaji: "hontōwa totemo totemo ureshikatta yo", myanmar: "တကယ်တော့ အရမ်းအရမ်း ဝမ်းသာခဲ့တယ်" },
      { start: 83, end: 90, japanese: "あぁ花火が夜空きれいに咲いて ちょっとセツナク", romaji: "ā hanabi ga yozora kirei ni sai te chotto setsunaku", myanmar: "အင်း မီးပန်းပွင့်တွေ ညအကောင်းမှာ လှပစွာပွင့်ကာ နည်းနည်းဝမ်းနည်းမိတယ်" },
      { start: 90, end: 97, japanese: "あぁ 風が時間とともに 流れる", romaji: "ā kaze ga jikan totomoni nagareru", myanmar: "အင်း လေက အချိန်နဲ့အတူ စီးဆင်းသွားတယ်" },
      { start: 97, end: 104, japanese: "嬉しくって楽しくって 冒険もいろいろしたね", romaji: "ureshikutte tanoshikutte bōken mo iroiro shi ta ne", myanmar: "ဝမ်းသာပြီး ပျော်ရွင်ကာ စွန့်စားမှုများစွာ လုပ်ခဲ့တယ်နော်" },
      { start: 104, end: 112, japanese: "二人の 秘密の基地の中", romaji: "ni nin no himitsu no kichi no naka", myanmar: "နှစ်ယောက်တည်း လျှို့ဝှက်ဌာနချိုထဲမှာ" },
      { start: 112, end: 125, japanese: "君と夏の終わり 将来の夢 大きな希望忘れない", romaji: "kimi to natsu no owari shōrai no yume ōkina kibō wasure nai", myanmar: "မင်းနဲ့ နွေရာသီကုန်ချိန် အနာဂတ်အိပ်မက် မြော်လင့်ချက်ကြီး မမေ့နိုင်ဘူး" },
      { start: 125, end: 133, japanese: "君が最後まで 心から「ありがとう」", romaji: "kimi ga saigo made kokorokara arigatō", myanmar: "မင်း နောက်ဆုံးထိ နှလုံးသားဆိုင်ရာ 'ကျေးဇူးတင်တယ်'" },
      { start: 133, end: 140, japanese: "叫んでいたこと 知っていたよ", romaji: "saken de i ta koto shitte i ta yo", myanmar: "အော်ဟစ်နေသည်ကို သိနေခဲ့တယ်" },
      { start: 140, end: 147, japanese: "涙をこらえて 笑顔でさよなら せつないよね", romaji: "namida o korae te egao de sayonara setsunai yo ne", myanmar: "မျက်ရည်တန့်ကာ အပြုံးနဲ့ နှုတ်ဆက်ခဲ့တယ် ဝမ်းနည်းစရာကောင်းတယ်နော်" },
      { start: 155, end: 163, japanese: "あぁ夏休みもあと少しで 終わっちゃうから", romaji: "ā natsuyasumi mo ato sukoshi de owatchau kara", myanmar: "အင်း နွေရာသီပိတ်ရက်လည်း နည်းနည်းနဲ့ ကုန်တော့မယ်မို့" },
      { start: 170, end: 178, japanese: "悲しくって寂しくって 喧嘩もいろいろしたね", romaji: "kanashikutte sabishikutte kenka mo iroiro shi ta ne", myanmar: "ဝမ်းနည်းပြီး တမ်းတကာ ရန်ဖြစ်မှုများစွာလည်း ရှိခဲ့တယ်နော်" },
      { start: 178, end: 186, japanese: "二人の 秘密の基地の中", romaji: "ni nin no himitsu no kichi no naka", myanmar: "နှစ်ယောက်တည်း လျှို့ဝှက်ဌာနချိုထဲမှာ" },
      { start: 197, end: 213, japanese: "涙をこらえて 笑顔でさよなら せつないよね", romaji: "namida o korae te egao de sayonara setsunai yo ne", myanmar: "မျက်ရည်တန့်ကာ အပြုံးနဲ့ နှုတ်ဆက်တယ် ဝမ်းနည်းစရာ" },
      { start: 219, end: 232, japanese: "手紙書くよ電話もするよ 忘れないでね僕のことを", romaji: "tegami kaku yo denwa mo suru yo wasure nai de ne boku no koto o", myanmar: "စာရေးမယ် ဖုန်းလည်း ဆက်မယ် ကျွန်တော့်ကို မမေ့နဲ့နော်" },
      { start: 232, end: 240, japanese: "いつまでも 二人の 基地の中", romaji: "itsu made mo ni nin no kichi no naka", myanmar: "အမြဲတမ်း နှစ်ယောက်တည်း ဌာနချိုထဲမှာ" },
      { start: 240, end: 252, japanese: "君と夏の終わり ずっと話して 夕日を見てから星を眺め", romaji: "kimi to natsu no owari zutto hanashi te yūhi o mi te kara hoshi o nagame", myanmar: "မင်းနဲ့ နွေကုန်ချိန် အမြဲစကားပြောကာ နေဝင်ကြည့်ပြီး ကြယ်တွေ ငေးကြည့်တယ်" },
      { start: 252, end: 262, japanese: "君の頬を 流れた涙は ずっと忘れない", romaji: "kimi no hō o nagare ta namida wa zutto wasure nai", myanmar: "မင်းပါးပေါ် စီးဆင်းသောမျက်ရည် အမြဲမမေ့နိုင်ဘူး" },
      { start: 247, end: 256, japanese: "君が最後まで 大きく手を振ってくれたこと きっと忘れない", romaji: "kimi ga saigo made ōkiku te o futte kure ta koto kitto wasure nai", myanmar: "မင်း နောက်ဆုံးထိ လက်ကြီးကြီး လှုပ်ပေးခဲ့တာ ဧကန်မမေ့နိုင်ဘူး" },
      { start: 262, end: 275, japanese: "だからこうして 夢の中でずっと永遠に…", romaji: "dakara kōshite yume no naka de zutto eien ni", myanmar: "ဒါကြောင့် ဒီလို အိပ်မက်ထဲမှာ အမြဲထာဝရ..." },
      { start: 281, end: 295, japanese: "10年後の8月 また出会えるの信じて", romaji: "10 nen go no 8 tsuki mata deaeru no shinji te", myanmar: "၁၀ နှစ်နောက် သြဂုတ်လမှာ တစ်ဖန်တွေ့မယ်လို့ ယုံကြည်တယ်" },
      { start: 295, end: 999, japanese: "涙をこらえて 笑顔でさよなら せつないよね 最高の思い出を…", romaji: "namida o korae te egao de sayonara setsunai yo ne saikō no omoide o", myanmar: "မျက်ရည်တန့်ကာ အပြုံးနဲ့ နှုတ်ဆက်တယ် ဝမ်းနည်းစရာ... အကောင်းဆုံးသောမှတ်ဉာဏ်..." },
    ],
  },
  {
    id: "3",
    title: "夜に駆ける / YOASOBI",
    titleMm: "Yoru ni Kakeru / YOASOBI",
    videoId: "l1QxlhkmFlg",
    level: "N3",
    subtitles: [
      { start: 1, end: 6, japanese: "沈むように溶けてゆくように", romaji: "shizumu yō ni toke te yuku yō ni", myanmar: "" },
      { start: 8, end: 14, japanese: "二人だけの空が広がる夜に", romaji: "ni nin ta ゙keno sora ka ゙ hiro ka ゙ru yoru ni", myanmar: "" },
      { start: 31, end: 33, japanese: "「さよなら」だけだった", romaji: "sayonara ta ゙keta゙tta", myanmar: "" },
      { start: 33, end: 37, japanese: "その一言で全てが分かった", romaji: "sono hitokoto te ゙ subete ka ゙ wakatta", myanmar: "" },
      { start: 37, end: 41, japanese: "日が沈み出した空と君の姿", romaji: "hi ka ゙ shizumi dashi ta sora to kimi no sugata", myanmar: "" },
      { start: 41, end: 46, japanese: "フェンス越しに重なっていた", romaji: "fensu goshi ni kasanatte i ta", myanmar: "" },
      { start: 46, end: 48, japanese: "初めて会った日から", romaji: "hajimete atta hi kara", myanmar: "" },
      { start: 48, end: 52, japanese: "僕の心の全てを奪った", romaji: "boku no kokoro no subete o ubatta", myanmar: "" },
      { start: 52, end: 56, japanese: "どこか儚い空気を纏う君は", romaji: "to ゙koka hakanai kūki o matou kimi wa", myanmar: "" },
      { start: 56, end: 60, japanese: "寂しい目をしてたんだ", romaji: "sabishii me o shi te tan ta ゙", myanmar: "" },
      { start: 60, end: 62, japanese: "いつだってチックタックと", romaji: "i tsu ta ゙tte chikku takku to", myanmar: "" },
      { start: 62, end: 63, japanese: "鳴る世界で何度だってさ", romaji: "naru sekai te ゙ nan do ta ゙ttesa", myanmar: "" },
      { start: 63, end: 65, japanese: "触れる心無い言葉", romaji: "fureru kokoronai kotoba", myanmar: "" },
      { start: 65, end: 66, japanese: "うるさい声に", romaji: "urusai koe ni", myanmar: "" },
      { start: 66, end: 68, japanese: "涙が零れそうでも", romaji: "namida ka ゙ kobore sō te ゙mo", myanmar: "" },
      { start: 68, end: 74, japanese: "ありきたりな喜びきっと二人なら見つけられる", romaji: "ari ki tari na ki hi ゙kitto ni nin nara mitsuke rareru", myanmar: "" },
      { start: 74, end: 78, japanese: "騒がしい日々に笑えない君に", romaji: "騒 ka ゙shii hibi ni warae nai kimi ni", myanmar: "" },
      { start: 78, end: 82, japanese: "思い付く限り眩しい明日を", romaji: "omoitsuku kagiri mabushii ashita o", myanmar: "" },
      { start: 82, end: 86, japanese: "明けない夜に落ちてゆく前に", romaji: "ake nai yoru ni ochi te yuku mae ni", myanmar: "" },
      { start: 86, end: 89, japanese: "僕の手を掴んでほら", romaji: "boku no te o tsukan te ゙hora", myanmar: "" },
      { start: 89, end: 93, japanese: "忘れてしまいたくて閉じ込めた日々も", romaji: "wasure te shimai taku te tozashi ゙ kome ta hibi mo", myanmar: "" },
      { start: 93, end: 97, japanese: "抱きしめた温もりで溶かすから", romaji: "dakishime ta nukumori te ゙ tokasu kara", myanmar: "" },
      { start: 97, end: 101, japanese: "怖くないよ いつか日が昇るまで", romaji: "kowaku nai yo itsuka nichi ka ゙ noboru mate ゙", myanmar: "" },
      { start: 101, end: 103, japanese: "二人でいよう", romaji: "ni nin te ゙iyou", myanmar: "" },
      { start: 118, end: 120, japanese: "君にしか見えない", romaji: "kimi ni shika mie nai", myanmar: "" },
      { start: 120, end: 124, japanese: "何かを見つめる君が嫌いだ", romaji: "nani ka o mitsumeru kimi ka ゙ kirai ta ゙", myanmar: "" },
      { start: 124, end: 126, japanese: "見惚れているかのような", romaji: "mihore te iru ka no yō na", myanmar: "" },
      { start: 126, end: 128, japanese: "恋するような", romaji: "koisuru yō na", myanmar: "" },
      { start: 128, end: 131, japanese: "そんな顔が嫌いだ", romaji: "sonna kao ka ゙ kirai ta ゙", myanmar: "" },
      { start: 132, end: 134, japanese: "信じていたいけど信じれないこと", romaji: "shin shi ゙teitaiketo゙ shin shi ゙renaikoto", myanmar: "" },
      { start: 134, end: 135, japanese: "そんなのどうしたってきっと", romaji: "sonna no to ゙ushitattekitto", myanmar: "" },
      { start: 135, end: 137, japanese: "これからだっていくつもあって", romaji: "korekara ta ゙tteikutsumoatte", myanmar: "" },
      { start: 137, end: 139, japanese: "そのたんび怒って泣いていくの", romaji: "sono tan hi ゙ okotte nai te iku no", myanmar: "" },
      { start: 139, end: 140, japanese: "それでもきっと", romaji: "sore te ゙mokitto", myanmar: "" },
      { start: 140, end: 141, japanese: "いつかはきっと", romaji: "itsuka wa kitto", myanmar: "" },
      { start: 141, end: 142, japanese: "僕らはきっと", romaji: "bokura wa kitto", myanmar: "" },
      { start: 142, end: 144, japanese: "分かり合えるさ信じてるよ", romaji: "wakari aeru sa shin shi ゙teruyo", myanmar: "" },
      { start: 144, end: 146, japanese: "信じてるよ", romaji: "shin shi ゙teruyo", myanmar: "" },
      { start: 161, end: 163, japanese: "もう嫌だって疲れたんだって", romaji: "mō iya ta ゙tte tsukare ta n ta ゙tte", myanmar: "" },
      { start: 163, end: 165, japanese: "がむしゃらに差し伸べた", romaji: "ka ゙musharani sashi shin e ゙ta", myanmar: "" },
      { start: 165, end: 167, japanese: "僕の手を振り払う君", romaji: "boku no te o furiharau kimi", myanmar: "" },
      { start: 167, end: 170, japanese: "もう嫌だって疲れたよなんて", romaji: "mō iya ta ゙tte tsukare ta yo nante", myanmar: "" },
      { start: 170, end: 174, japanese: "本当は僕も言いたいんだ", romaji: "hontōwa boku mo ii tai n ta ゙", myanmar: "" },
      { start: 175, end: 176, japanese: "ほらまたチックタックと", romaji: "hora mata chikku takku to", myanmar: "" },
      { start: 176, end: 178, japanese: "鳴る世界で何度だってさ", romaji: "naru sekai te ゙ nan do ta ゙ttesa", myanmar: "" },
      { start: 178, end: 180, japanese: "君の為に用意した言葉", romaji: "kimi no tame ni yōi shi ta kotoba", myanmar: "" },
      { start: 180, end: 181, japanese: "どれも届かない", romaji: "to ゙remo todoke ka nai", myanmar: "" },
      { start: 181, end: 183, japanese: "「終わりにしたい」だなんてさ", romaji: "owari ni shi tai ta ゙nantesa", myanmar: "" },
      { start: 183, end: 185, japanese: "釣られて言葉にした時", romaji: "tsura re te kotoba ni shi ta toki", myanmar: "" },
      { start: 185, end: 189, japanese: "君は初めて笑った", romaji: "kimi wa hajimete waratta", myanmar: "" },
      { start: 191, end: 195, japanese: "騒がしい日々に笑えなくなっていた", romaji: "騒 ka ゙shii hibi ni warae naku natte i ta", myanmar: "" },
      { start: 195, end: 198, japanese: "僕の目に映る君は綺麗だ", romaji: "boku no me ni utsuru kimi wa kirei ta ゙", myanmar: "" },
      { start: 198, end: 202, japanese: "明けない夜に溢れた涙も", romaji: "ake nai yoru ni afure ta namida mo", myanmar: "" },
      { start: 202, end: 206, japanese: "君の笑顔に溶けていく", romaji: "kimi no egao ni toke te iku", myanmar: "" },
      { start: 207, end: 211, japanese: "変わらない日々に泣いていた僕を", romaji: "kawara nai hibi ni nai te i ta boku o", myanmar: "" },
      { start: 211, end: 215, japanese: "君は優しく終わりへと誘う", romaji: "kimi wa yasashiku owari e to sasou", myanmar: "" },
      { start: 215, end: 219, japanese: "沈むように溶けてゆくように", romaji: "shizumu yō ni toke te yuku yō ni", myanmar: "" },
      { start: 219, end: 222, japanese: "染み付いた霧が晴れる", romaji: "shimitsui ta kiri ka ゙ hareru", myanmar: "" },
      { start: 222, end: 226, japanese: "忘れてしまいたくて閉じ込めた日々に", romaji: "wasure te shimai taku te tozashi ゙ kome ta hibi ni", myanmar: "" },
      { start: 226, end: 230, japanese: "差し伸べてくれた君の手を取る", romaji: "sashi shin e ゙tekureta kun no te o toru", myanmar: "" },
      { start: 230, end: 235, japanese: "涼しい風が空を泳ぐように今", romaji: "suzushii kaze ka ゙ sora o 泳 ku ゙youni ima", myanmar: "" },
      { start: 235, end: 237, japanese: "吹き抜けていく", romaji: "fukinuke te iku", myanmar: "" },
      { start: 237, end: 240, japanese: "繋いだ手を離さないでよ", romaji: "tsunai ta ゙ shu o hanasa nai te ゙yo", myanmar: "" },
      { start: 240, end: 243, japanese: "二人今、夜に駆け出していく", romaji: "ni nin ima yoru ni kakedashi te iku", myanmar: "" },
      { start: 258, end: 262, japanese: "Thanks for watching!", romaji: "Thanks for watching !", myanmar: "" },
    ],
  },
  {
    id: "4",
    title: "Lemon / 米津玄師",
    titleMm: "Lemon / Kenshi Yonezu",
    videoId: "MxjXe5eg6vY",
    level: "N3",
    subtitles: [
      { start: 2, end: 7, japanese: "夢ならばどれほどよかったでしょう", romaji: "yume nara wa ゙to゙rehoto゙yokattate゙shou", myanmar: "" },
      { start: 8, end: 13, japanese: "未だにあなたのことを夢にみる", romaji: "mi ta ゙nianatanokotoo yume ni miru", myanmar: "" },
      { start: 13, end: 18, japanese: "忘れた物を取りに帰るように", romaji: "wasure ta mono o tori ni kaeru yō ni", myanmar: "" },
      { start: 18, end: 24, japanese: "古びた思い出の埃を払う", romaji: "ko hi ゙ta omoide no hokori o harau", myanmar: "" },
      { start: 27, end: 32, japanese: "戻らない幸せがあることを", romaji: "modora nai shiawase ka ゙arukotoo", myanmar: "" },
      { start: 32, end: 38, japanese: "最後にあなたが教えてくれた", romaji: "saigo ni anata ka ゙ oshie te kure ta", myanmar: "" },
      { start: 38, end: 43, japanese: "言えずに隠してた昏い過去も", romaji: "ie su ゙ni kakushi te ta 昏 i kako mo", myanmar: "" },
      { start: 44, end: 49, japanese: "あなたがいなきゃ永遠に昏いまま", romaji: "anata ka ゙inakya eien ni 昏 ima ma", myanmar: "" },
      { start: 49, end: 52, japanese: "きっともうこれ以上", romaji: "kitto mō kore ijō", myanmar: "" },
      { start: 52, end: 55, japanese: "傷つくことなど", romaji: "kizutsuku koto na to ゙", myanmar: "" },
      { start: 55, end: 60, japanese: "ありはしないとわかっている", romaji: "ari wa shi nai to wakatte iru", myanmar: "" },
      { start: 60, end: 65, japanese: "あの日の悲しみさえ あの日の苦しみさえ", romaji: "ano hi no kanashimi sae ano hi no kurushimi sae", myanmar: "" },
      { start: 65, end: 71, japanese: "そのすべてを愛してた あなたとともに", romaji: "sono su e ゙teo aishi te ta anata totomoni", myanmar: "" },
      { start: 71, end: 76, japanese: "胸に残り離れない 苦いレモンの匂い", romaji: "mune ni nokori hanare nai nigai remon no nioi", myanmar: "" },
      { start: 77, end: 82, japanese: "雨が降り止むまでは帰れない", romaji: "ame ka ゙ ori tome mumate゙ha kaere nai", myanmar: "" },
      { start: 82, end: 88, japanese: "今でもあなたはわたしの光", romaji: "ima te ゙moanatahawatashino kō", myanmar: "" },
      { start: 99, end: 104, japanese: "暗闇であなたの背をなぞった", romaji: "kurayami te ゙anatano se o naso ゙tta", myanmar: "" },
      { start: 104, end: 110, japanese: "その輪郭を鮮明に覚えている", romaji: "sono rinkaku o semmei ni oboe te iru", myanmar: "" },
      { start: 110, end: 115, japanese: "受け止めきれないものと出会うたび", romaji: "uketome kire nai mono to deau ta hi ゙", myanmar: "" },
      { start: 115, end: 121, japanese: "溢れてやまないのは涙だけ", romaji: "afure te yama nai no wa namida ta ゙ke", myanmar: "" },
      { start: 121, end: 127, japanese: "何をしていたの 何を見ていたの", romaji: "nani o shi te i ta no nani o mi te i ta no", myanmar: "" },
      { start: 127, end: 131, japanese: "わたしの知らない横顔で", romaji: "watashi no shira nai yokogao te ゙", myanmar: "" },
      { start: 131, end: 137, japanese: "どこかであなたが今 わたしと同じ様な", romaji: "to ゙kokate゙anataka゙ ima watashi to dō shi ゙ sama na", myanmar: "" },
      { start: 137, end: 142, japanese: "涙にくれ 淋しさの中にいるなら", romaji: "namida ni kure sabishi sa no naka ni iru nara", myanmar: "" },
      { start: 142, end: 148, japanese: "わたしのことなどどうか 忘れてください", romaji: "watashi no koto na to ゙to゙uka wasure te ku ta ゙sai", myanmar: "" },
      { start: 148, end: 154, japanese: "そんなことを心から願うほどに", romaji: "sonna koto o kokorokara negau ho to ゙ni", myanmar: "" },
      { start: 154, end: 159, japanese: "今でもあなたはわたしの光", romaji: "ima te ゙moanatahawatashino kō", myanmar: "" },
      { start: 163, end: 168, japanese: "自分が思うより", romaji: "jibun ka ゙ omou yori", myanmar: "" },
      { start: 168, end: 173, japanese: "恋をしていたあなたに", romaji: "koi o shi te i ta anata ni", myanmar: "" },
      { start: 174, end: 179, japanese: "あれから思うように", romaji: "are kara omou yō ni", myanmar: "" },
      { start: 179, end: 184, japanese: "息ができない", romaji: "iki ka ゙te゙kinai", myanmar: "" },
      { start: 184, end: 190, japanese: "あんなに側にいたのに", romaji: "annani gawa ni i ta noni", myanmar: "" },
      { start: 190, end: 195, japanese: "まるで嘘みたい", romaji: "maru te ゙ uso mitai", myanmar: "" },
      { start: 195, end: 201, japanese: "とても忘れられない", romaji: "totemo wasure rare nai", myanmar: "" },
      { start: 201, end: 209, japanese: "それだけが確か", romaji: "sore ta ゙keka゙ tashika", myanmar: "" },
      { start: 212, end: 214, japanese: "あの日の悲しみさえ", romaji: "ano hi no kanashimi sae", myanmar: "" },
      { start: 214, end: 217, japanese: "あの日の苦しみさえ", romaji: "ano hi no kurushimi sae", myanmar: "" },
      { start: 217, end: 220, japanese: "そのすべてを愛してた", romaji: "sono su e ゙teo aishi te ta", myanmar: "" },
      { start: 220, end: 223, japanese: "あなたとともに", romaji: "anata totomoni", myanmar: "" },
      { start: 223, end: 228, japanese: "胸に残り離れない 苦いレモンの匂い", romaji: "mune ni nokori hanare nai nigai remon no nioi", myanmar: "" },
      { start: 228, end: 234, japanese: "雨が降り止むまでは帰れない", romaji: "ame ka ゙ ori tome mumate゙ha kaere nai", myanmar: "" },
      { start: 234, end: 239, japanese: "切り分けた果実の片方の様に", romaji: "kiriwake ta kajitsu no katahō no yō ni", myanmar: "" },
      { start: 239, end: 246, japanese: "今でもあなたはわたしの光", romaji: "ima te ゙moanatahawatashino kō", myanmar: "" },
      { start: 253, end: 255, japanese: "Thanks for watching!!", romaji: "Thanks for watching !!", myanmar: "" },
    ],
  },
  {
    id: "5",
    title: "Pretender / Official髭男dism",
    titleMm: "Pretender / Official HIGE DANdism",
    videoId: "TnrVt--rXHY",
    level: "N2",
    subtitles: [
      { start: 23, end: 39, japanese: "君とのラブストーリー それは予想通り いざ始まればひとり芝居だ ずっとそばにいたって 結局ただの観客だ", romaji: "kimi to no rabusutōrī sore wa yosō dōri iza hajimare ba hitori shibai da zutto soba ni itatte kekkyoku tada no kankyaku da", myanmar: "" },
      { start: 39, end: 58, japanese: "感情のないアイムソーリー それはいつも通り 慣れてしまえば悪くはないけど 君とのロマンスは人生柄 続きはしないことを知った", romaji: "kanjō no nai aimusōrī sore wa itsumo tōri nare te shimae ba waruku wa nai kedo kimi to no romansu wa jinsei gara tsuzuki wa shi nai koto o shitta", myanmar: "" },
      { start: 58, end: 71, japanese: "もっと違う設定で　もっと違う関係で 出会える世界線　選べたらよかった", romaji: "motto chigau settei de motto chigau kankei de deaeru sekai sen erabe tara yokatta", myanmar: "" },
      { start: 71, end: 85, japanese: "もっと違う性格で　もっと違う価値観で 愛を伝えられたらいいな　そう願っても無駄だから", romaji: "motto chigau seikaku de motto chigau kachi kan de ai o tsutae rare tara ii na sō negatte mo muda da kara", myanmar: "" },
      { start: 85, end: 106, japanese: "グッバイ 君の運命のヒトは僕じゃない 辛いけど否めない　でも離れ難いのさ その髪に触れただけで　痛いや　いやでも 甘いな　いやいや", romaji: "gutsu bai kimi no ummei no hito wa boku ja nai tsurai kedo iname nai demo hanare gatai no sa sono kami ni fure ta dake de itai ya iya demo amai na iya iya", myanmar: "" },
      { start: 106, end: 131, japanese: "グッバイ それじゃ僕にとって君は何？ 答えは分からない　分かりたくもないのさ たったひとつ確かなことがあるとするのならば 「君は綺麗だ」", romaji: "gutsu bai sore ja boku nitotte kimi wa nani ? kotae wa wakara nai wakari taku mo nai no sa tatta hitotsu tashika na koto ga aru to suru no nara ba kimi wa kirei da", myanmar: "" },
      { start: 133, end: 153, japanese: "誰かが偉そうに 語る恋愛の論理 何ひとつとしてピンとこなくて 飛行機の窓から見下ろした 知らない街の夜景みたいだ", romaji: "dare ka ga era sō ni kataru ren'ai no ronri nani hitotsu toshite pin toko naku te hikōki no mado kara mioroshi ta shira nai machi no yakei mitai da", myanmar: "" },
      { start: 153, end: 164, japanese: "もっと違う設定で　もっと違う関係で 出会える世界線　選べたらよかった", romaji: "motto chigau settei de motto chigau kankei de deaeru sekai sen erabe tara yokatta", myanmar: "" },
      { start: 164, end: 180, japanese: "いたって純な心で　叶った恋を抱きしめて 「好きだ」とか無責任に言えたらいいな そう願っても虚しいのさ", romaji: "itatte jun na kokoro de kanatta koi o dakishime te suki da toka musekinin ni ie tara ii na sō negatte mo munashii no sa", myanmar: "" },
      { start: 180, end: 204, japanese: "グッバイ 繋いだ手の向こうにエンドライン 引き伸ばすたびに　疼きだす未来には 君はいない　その事実に Cry... そりゃ苦しいよな", romaji: "gutsu bai tsunai da te no mukō ni endorain hikinobasu tabi ni uzuki dasu mirai ni wa kimi wa i nai sono jijitsu ni Cry ... sorya kurushii yo na", myanmar: "" },
      { start: 221, end: 242, japanese: "グッバイ 君の運命のヒトは僕じゃない 辛いけど否めない　でも離れ難いのさ その髪に触れただけで　痛いや いやでも　甘いな　いやいや", romaji: "gutsu bai kimi no ummei no hito wa boku ja nai tsurai kedo iname nai demo hanare gatai no sa sono kami ni fure ta dake de itai ya iya demo amai na iya iya", myanmar: "" },
      { start: 242, end: 266, japanese: "グッバイ それじゃ僕にとって君は何？ 答えは分からない　分かりたくもないのさ たったひとつ確かなことがあるとするのならば 「君は綺麗だ」", romaji: "gutsu bai sore ja boku nitotte kimi wa nani ? kotae wa wakara nai wakari taku mo nai no sa tatta hitotsu tashika na koto ga aru to suru no nara ba kimi wa kirei da", myanmar: "" },
      { start: 266, end: 276, japanese: "それもこれもロマンスの定めなら　悪くないよな", romaji: "sore mo kore mo romansu no sadame nara waruku nai yo na", myanmar: "" },
      { start: 276, end: 290, japanese: "永遠も約束もないけれど 「とても綺麗だ」", romaji: "eien mo yakusoku mo nai keredo totemo kirei da", myanmar: "" },
    ],
  },
  {
    id: "6",
    title: "粉雪 / レミオロメン",
    titleMm: "Konayuki / Remioromen",
    videoId: "Tic_P-ujcQM",
    level: "N3",
    subtitles: [
      { start: 25, end: 36, japanese: "粉雪舞う季節はいつもすれ違い", romaji: "koyuki mau kisetsu wa itsumo surechigai", myanmar: "" },
      { start: 36, end: 47, japanese: "人混みに紛れても同じ空見てるのに", romaji: "hitogomi ni magire te mo onaji sora mi teru noni", myanmar: "" },
      { start: 47, end: 55, japanese: "風に吹かれて 似たように凍えるのに", romaji: "kaze ni fuka re te ni ta yō ni kogoeru noni", myanmar: "" },
      { start: 60, end: 72, japanese: "僕は君の全てなど知ってはいないだろう", romaji: "boku wa kimi no subete nado shitte wa i nai daro u", myanmar: "" },
      { start: 72, end: 82, japanese: "それでも一億人から君を見つけたよ", romaji: "soredemo ichi oku nin kara kimi o mitsuke ta yo", myanmar: "" },
      { start: 82, end: 91, japanese: "根拠はないけど 本気で思ってるんだ", romaji: "konkyo wa nai kedo honki de omotteru n da", myanmar: "" },
      { start: 91, end: 97, japanese: "些細な言い合いもなくて", romaji: "sasai na īai mo naku te", myanmar: "" },
      { start: 97, end: 104, japanese: "同じ時間を生きてなどいけない", romaji: "onaji jikan o iki te nado ike nai", myanmar: "" },
      { start: 104, end: 110, japanese: "素直になれないなら", romaji: "sunao ni nare nai nara", myanmar: "" },
      { start: 110, end: 121, japanese: "喜びも悲しみも虚しいだけ", romaji: "yorokobi mo kanashimi mo munashii dake", myanmar: "" },
      { start: 121, end: 133, japanese: "粉雪 ねえ 心まで白く染められたなら", romaji: "koyuki nē kokoro made shiroku some rare ta nara", myanmar: "" },
      { start: 133, end: 143, japanese: "二人の孤独を分け合う事が出来たのかい", romaji: "ni nin no kodoku o wakeau koto ga deki ta no kai", myanmar: "" },
      { start: 154, end: 165, japanese: "僕は君の心に耳を押し当てて", romaji: "boku wa kimi no kokoro ni mimi o oshi ate te", myanmar: "" },
      { start: 165, end: 176, japanese: "その声のする方へすっと深くまで", romaji: "sono koe no suru hō e sutto fukaku made", myanmar: "" },
      { start: 176, end: 185, japanese: "下りてゆきたい そこでもう一度会おう", romaji: "ori te yuki tai sokode mōichido aō", myanmar: "" },
      { start: 185, end: 191, japanese: "分かり合いたいなんて", romaji: "wakari ai tai nante", myanmar: "" },
      { start: 191, end: 197, japanese: "上辺を撫でていたのは僕の方", romaji: "uwabe o nade te i ta no wa boku no hō", myanmar: "" },
      { start: 197, end: 203, japanese: "君のかじかんだ手も", romaji: "kimi no kajikan da te mo", myanmar: "" },
      { start: 203, end: 215, japanese: "握りしめることだけで繋がってたのに", romaji: "nigirishimeru koto dake de tsunagatte ta noni", myanmar: "" },
      { start: 215, end: 227, japanese: "粉雪 ねえ 永遠を前にあまりに脆く", romaji: "koyuki nē eien o mae ni amarini moroku", myanmar: "" },
      { start: 227, end: 236, japanese: "ざらつくアスファルトの上シミになってゆくよ", romaji: "zaratsuku asufaruto no ue shimi ni natte yuku yo", myanmar: "" },
      { start: 259, end: 271, japanese: "粉雪 ねえ 時に頼りなく心は揺れる", romaji: "koyuki nē tokini tayori naku kokoro wa yureru", myanmar: "" },
      { start: 271, end: 282, japanese: "それでも僕は君のこと守り続けたい", romaji: "soredemo boku wa kimi no koto mamori tsuzuke tai", myanmar: "" },
      { start: 282, end: 294, japanese: "粉雪 ねえ 心まで白く染められたなら", romaji: "koyuki nē kokoro made shiroku some rare ta nara", myanmar: "" },
      { start: 294, end: 307, japanese: "二人の孤独を包んで空にかえすから", romaji: "ni nin no kodoku o tsutsun de sora ni kaesu kara", myanmar: "" },
    ],
  },
];
